### ISSUE TITLE
Take subject line into consideration when threading (feature request)

### ISSUE THREAD

**Issue by thblt** [djcb/mu#1014]
## Expected or desired behavior

I'd like to request an option, similar to the one provided by Gnus, to consider mails with:

 - headers that imply they belong to an existing thread (ie are a reply to a previous message);
 - but a different subject line than the mail they're supposed to respond to,

as part of a new, different thread.

The rationale for this request is that on a lot of non-technical mailing-lists I'm subscribed to, people tend to “reply” to old mails to send a new announcement to the same set of recipients, by changing the subject line and erasing previous contents.  This creates long “threads”, some ranging for multiple months, even years, of completely unrelated messages.  I understand this is not good mail etiquette, but I have no hope of changing everybody's habits.

## Actual behavior

mu/mu4e always ignore subject when threading.

**Comment by djcb** [comment]
That's annoying... but on the other hand, people continue threads while changing the subject (this happens frequently e.g. in the emacs mailing list). Don't want to break those threads.

Both are a bit suboptimal, as you say. But since we have a working method (which is "technically correct"), I'll settle for the status-quo. Sorry!
