### ISSUE TITLE
mu would need to be ported to webkitgtk4

### ISSUE THREAD

**Issue by pacho2** [djcb/mu#1026]
Most distributions are trying to move to webkitgtk4 and kill older versions because of them being security vulnerable and unmaintained. Hence, sooner or later we will need mu to be ported to webkitgtk4 or, at least, stop using older webkit-gtk versions

Thanks a  lot

**Comment by norbusan** [comment]
Agreed, as the Debian maintainer I have to remove mug from the packages now as webkit v3 is being removed soon.

Would be nice to see it ported to v4.

Thanks

**Comment by montaropdf** [comment]
What is the status on this topic?

On Fedora 27, webkitgtk3 is not available anymore, so I cannot compile msg2pdf.

**Comment by eklitzke** [comment]
I fixed the build system and some of the headers, which I think is a significant amount of the work. This lets you get all the way through the build phase until you compile `mu-message-body-view.c`, which is actually the only file with WebKit code in it. That fails due to some API changes between webkit and webkit2. You can find this work in my `webkitgtk4` branch here: https://github.com/eklitzke/mu/tree/webkitgtk4

The amount of code remaining that needs to be ported is really not that much, someone could probably figure it out in a few hours. If someone wants to pick up from my branch that would be great. I might dig in more at some point, but I don't really have that much need to use the GUI client so no promises.

**Comment by metalipa** [comment]
Would it be possible to finish porting mu to webkitgtk4? msg2pdf still does not compile.

**Comment by djcb** [comment]
`mug` has been ported to the new webkit; `msg2pdf` compiles, but doesn't quite work at this moment; volunteers welcome!
