### ISSUE TITLE
`mu4e-compose-resend` clobbers multipart/mixed mail

### ISSUE THREAD

**Issue by eigengrau** [djcb/mu#1051]
## Expected or desired behavior

While I take it from previous issues that it is unavoidable for MIME-encoded mail to be shown in raw form after issuing `mu4e-compose-resend`, I am expecting the Content-Type header to be sent unmodified.

## Actual behavior

When issuing `mu4e-compose-resend` on a multipart/mixed mail, editing the recipient and sending the message, the message is sent out as `Content-Type: text/plain`, even when the mu4e-compose buffer was showing `multipart/mixed`.

## Steps to reproduce

See above.

## Versions of mu, mu4e/emacs, operating system etc.

mu4e from 21b637f2

## Bonus question

I am curious why resend cannot decode MIME messages when creating a compose buffer. My usecase is using my old (or other peoples’) mail as a template for new, unrelated messages. `mu4e-compose-edit` will only work for draft mail; `mu4e-compose-forward` will decode MIME messages properly, but will quote them. Basically, I am looking for `mu4e-compose-forward` without quoting. Am I missing some existing function for this?

**Comment by mbunkus** [comment]
I'm pretty annoyed by this, too. Back when I was using mutt I was often using its bounce or edit feature: bouncing for redirecting email to e.g. my company's helpdesk address (when customers send me stuff that rightfully should have gone to the helpdesk), and the "edit again" feature for using an existing email as a template for someone else. Forwarding is not the same and doesn't solve my use case.

At the moment mu4e has neither a working bounce functionality (`mu4e-compose-resend` requires modifying the `To:` header while real bouncing only changes the envelope recipient) nor a working "edit again/send again" feature due to this particular bug.

Both issues are painful enough for me to make me reconsider going back to mutt, which I would find rather unfortunate.

**Comment by mbunkus** [comment]
I've implemented a workaround that works well enough for me. It's a bad hack, therefore it isn't suitable for inclusion, but it may be of help to @eigengrau

`mu` and therefore by extension `mu4e` knows the following types when composing mails: `new`, `reply`, `forward`, `edit` and `resend`. They should all be self-explanatory as they correspond to the similarly named functions we use for creating new mail.

What happens when you press e.g. `r` for replying is:

* `mu4e-compose-reply` is called which just calls `mu4e-compose` with the type `reply`.
* `mu4e-compose` does a lot of stuff, but it boils down to it calling `mu` itself with a `cmd:compose` and `type:reply`.
* `mu` now retrieves the message the user is replying to. Only if the type is `forward` does `mu` also retrieve the attachments (this is important for our "send again" function).
* When the answer from `mu` arrives asynchronously, the callback function `mu4e~compose-handler` is called with the message as an argument.
* `mu4e~compose-handler` now calls `mu4e-draft-open` which does a case on the type and calls the function ultimately responsible for populating the new message with both headers and body; in our example: `mu4e~draft-reply-construct`

Phew!

So what I basically need is:

1. A new message with at least the most important header fields set the same as the message I'm trying to send again (`From`, `To`, `Cc` and `Subject`).
2. the body identical to the body of the original message and
3. all attachments being present.

Unfortunately adding another type to the above workflow would require adjusting both `mu` and `mu4e` as the type list is hardcoded in both programs, and in mu4e's case in many places. Therefore this is out for my quick hack.

Point 3 means that only type `forward` makes sense as that's the only type for which `mu` returns the attachments for the original message.

So here's what I've come up with:

1. I add a new function for "sending again" that initiates a `forward` compose action and stores the fact that I'm really just trying to "send again" and not actually to forward (there's a new global variable for storing this fact).
2. I bind that function in both the headers and view modes.
3. I now need to change the function responsible for populating the buffer with the message content, and that's `mu4e~draft-forward-construct`. For this I use an around-advice:
  1. If the new variable was set in step 1, then I know that the current buffer is really a "send again" action, and I populate it accordingly. I also un-set that variable.
  2. Otherwise I call the original `mu4e~draft-forward-construct` function.

And here's the code (without the key bindings for `mo-mu4e-compose-send-again`):

```lisp
(defvar mo-mu4e-next-forward-compose-is-send-again nil
  "Set to t if currently calling `mo-mu4e-compose-send-again'.")

(defun mo-mu4e-compose-send-again ()
  "Compose the message anew."
  (interactive)
  (setq mo-mu4e-next-forward-compose-is-send-again t)
  (mu4e-compose-forward))

(defun mo-mu4e-draft-forward-construct (orig-fun &rest args)
  (if (not mo-mu4e-next-forward-compose-is-send-again)
      (apply orig-fun args)

    (setq mo-mu4e-next-forward-compose-is-send-again nil)
    (let* ((origmsg (car args)))
      (concat
       (mu4e~draft-header "From" (mu4e~draft-recipients-list-to-string
                                  (mu4e-message-field origmsg :from)))
       (mu4e~draft-header "To" (mu4e~draft-recipients-list-to-string
                                (mu4e-message-field origmsg :to)))
       (mu4e~draft-header "Cc" (mu4e~draft-recipients-list-to-string
                                (mu4e-message-field origmsg :cc)))
       (mu4e~draft-common-construct)
       (mu4e~draft-header "Subject" (or (plist-get origmsg :subject) ""))
       "\n\n"
       (mu4e-message-body-text origmsg)))))

(advice-remove 'mu4e~draft-forward-construct #'mo-mu4e-draft-forward-construct)
(advice-add 'mu4e~draft-forward-construct :around #'mo-mu4e-draft-forward-construct)
```

**Comment by wilhelmy** [comment]
Can we get this merged?

**Comment by jvshahid** [comment]
It's unclear to me how the @mbunkus solution fixes the `content-type` header issue.  @djcb I confirm that `Content-Type` isn't reserved in the email.  Any idea how to workaround it ?

**Comment by djcb** [comment]
Note, this works now (1.5.11 and later), with the to-be-resent message available its full glory, with the new (default) gnus-based message viewer.
