### ISSUE TITLE
mu4e-update-interval makes unread messages header view very hard to use

### ISSUE THREAD

**Issue by ian-kelling** [djcb/mu#1055]
## Expected or desired behavior

From the main view, type bu for the unread messages header view.

View a message.

Mark it.

The message becomes marked.

## Actual behavior

Mark it.

Error, if update-interval has happened since the time you opened it.

In that case, the currently viewed message has been removed from the header list because it's no longer unread, so mu4e has an error about how it can't find the message.

versions:
a recent emacs from git commit 244de7b0ed3bb2
a recent mu from git commit ff94595

**Comment by seanfarley** [comment]
Aha, I was about to file a report of a locking issue but saw this issue. This is quite problematic and I wonder what the right solution would be (perhaps I'm overthinking it).

P.S. Would the mailing list be a better place to discuss this?

**Comment by crispinb** [comment]
I've recently started using mu4e and find this a significant usability problem. It makes my workflow (read, then archive/refile) difficult as (with a short update interval) the header often disappears while I'm reading.

`mu4e-headers-auto-update` off isn't an optimal solution for me as I prefer to keep an unread search visible most of the time, and do want that to refresh. I also get `Cannot find message in headers buffer` errors from time to time while I'm reading.

I don't know enough about mu4e (or emacs for that matter to know what the best solution is. Would it be possible to add a setting which inhibits header refresh only while a message view is open?

**Comment by seanfarley** [comment]
For whatever my opinion is worth (asymptotically close to zero), I have been quite happy with turning off autoupdate. It had a subtle behavioral change of interrupting my work with a notification to change into me sitting time aside (at my choosing) to check email. Not a solution at all (especially since it made obsolete my notification lisp code) but quite happy with the new workflow.

**Comment by crispinb** [comment]
I agree an asynchronous email workflow can be viable, even preferable.  But there are people who prefer otherwise, and circumstances that dictate it, in which cases  the current mu4e behaviour isn't ideal.

**Comment by seanfarley** [comment]
In the past, I tried to solve this but it is quite challenging. At its core, it's a cache invalidation / transaction problem which are notoriously difficult. As I went down that path, I ended up needing to create a way to save the current state both the maildir and the view. That led to trying to figure out a way to merge state after a sync is done, at which point I gave up because it was too difficult.

Perhaps a hybrid (and easy) solution would be to not run updates while the views are open (but I'm not sure off the top of my head there's a way to check for that) and only run when it's "safe." Alternatively, just disable the setting entirely as it's too confusing in its current implementation.

Though, I'd love if @djcb had thoughts on a slick implementation that would correctly solve the locking / transaction hornet's nest 😄

**Comment by crispinb** [comment]
OK thanks. A reasonable workaround for now would be to use an unread search for asynchronous sweeps, but switch to the inbox maildir when keeping an eye on things.

**Comment by theophilusx** [comment]
What is your update interval?

What versions of Emacs and mu?

I'm using the current Git head with auto-update on and a similar
workflow, but probably a much longer interval. I don't see this issue.

I check for mail every 10 minutes. I find this a good balance and of
course, can always do a manual update if necessary. I can often take
longer to compose a message than that and can often leave a message view
open for hours while I do other stuff, so I'm suspecting the issue you
are seeing may be related to the mu version. I am also using the message
view based on gnus, which was perhaps still a little experimental in
current stable versions, but is quite stable in current dev version. The
git head version seems pretty stable at present and I suspect is not far
from being released. Might be worth giving it a try.

**Comment by crispinb** [comment]
I'm on Emacs 26.3 and mu 1.2.0. Update interval is 2m - shorter than needed really but I've just circled the wagons back to local maildirs after some years on webmail, and am adjusting.

Thanks for the mu  version suggestion - mine is as packaged by my distribution (Ubuntu). I'll give the latest a try if I can compile it without a huge dependencies kerfuffle.

**Comment by theophilusx** [comment]
I'm also on ubuntu and had no issues building mu. I'm also using the
mbsync for the imap retrieval stuff (from Gmail, outlook and an MS
Exchange (that is really using o365). I also have thunderbird configured
as a 'backup', though seldom use it anymore.

Note there have been some important changes, so check the NEWS file if
you update to current dev version.

**Comment by crispinb** [comment]
Thanks @theophilusx - similar setup with mbsync here. Following your suggestion I installed from source (1.4 popped up in the nick of time).

The issue still arises for me, but I realise now that if you mark an email, it prevents updates removing it from the header view. That's good enough for my purpose as I'm going to refile or delete in all cases anyway. Combined with increasing the update interval (which I was always planning to do) it's an effective workaround.
