### ISSUE TITLE
prevent mu4e convert html email to text when replying email

### ISSUE THREAD

**Issue by csfreebird** [djcb/mu#1159]
## Expected or desired behavior

If some people send emails to me, they use outlook or other modern email client, writing html email with image. When I reply these html emails, mu4e usually converted them into text content, it make other people uncomfortable. They complain to me why use this email client(mu4e). I want to know if it has a way to keep email original format without changing it when replying emails using mu4e(maybe org mode can help, but I do not know).

Please describe the behavior you expected / want

## Actual behavior

Please describe the behavior you are actually seeing. 

For bug-reports, if applicable, include error messages, emacs stack
traces etc. Try to be as specific as possible - when do you see this
happening? Does it happen always?  Sometimes? How often?

## Steps to reproduce

For bug-reports, please describe in as much details as possible how
one can reproduce the problem*.

**Comment by jasoncyu** [comment]
Possibly related (https://github.com/djcb/mu/issues/1051)

**Comment by djcb** [comment]
Unfortunately, I don't think that is (reasonably) possible in emacs, since we must convert to text to be able to read the html. We can't really use the existing mime-parts, but even if we did and leave those mime-parts as-is, it would give a rather sucky UI since you might even be able to read what you're replying too.
