### ISSUE TITLE
RFE: secondary sort criterion

### ISSUE THREAD

**Issue by backerman** [djcb/mu#1215]
## Expected or desired behavior

I would like to be able to sort headers by multiple criteria; e.g., by sender and then timestamp.

## Actual behavior

Only one sort criterion can be selected; the sort is not stable, so messages with an identical value of the new criterion are ordered essentially randomly.

## Steps to reproduce

1. Open a header view.
2. Sort by any criterion.
3. Sort by a different criterion. Observe that the sort is not stable.

## Versions of mu, mu4e/emacs, operating system etc.

Arch, Emacs 25.3, Linux 4.15.13-1 (standard Arch package), mu/mu4e 1.0 release.

## Additional information

Should the sort not being stable be a separate issue?

**Comment by djcb** [comment]
Would be useful, but this is sadly rather hard to implement, since the underlying Xapian database does not support it, and we can't really do it on the client (emacs) side without things becoming much slower.

Xapian doing the sorting also means that the query is re-run, making the sort order unstable. 

So, unfortunately will have to decline this.
