### ISSUE TITLE
PDF version of the manual?

### ISSUE THREAD

**Issue by x-ji** [djcb/mu#1227]
Sorry if this question is a bit noobish. I'm trying to produce the mu4e manual in PDF format so that I can read it on an e-ink screen, but so far I've failed to do so. I'm not familiar with the `info` format. [An SE question](https://unix.stackexchange.com/questions/62941/how-do-you-output-an-info-page-to-pdf) suggests running `texi2pdf`, however when I try to run `texi2pdf mu4e.texi`, I get an error about not being able to find  `version.texi`.

How can I generate a PDF of the manual? Would it be sensible to also distribute a PDF version of the manual by default? Thanks!

**Comment by edumerco** [comment]
Hello Xiang.

> Sorry if this question is a noobish. I'm trying to produce the 
> mu4e manual in PDF format so that I can read it on an e-ink 
> screen, [...] How can I generate a PDF of the manual? Would it 
> be sensible to also distribute a PDF version of the manual by 
> default?

I would point more to an epub format since it is more accesible, 
adaptable and an open standard. Essentially, it's not much more 
than a compressed html with some bells and whistles. ;)

A pdf (while more used in the desktop computer world) is more 
appropiate when you want to preserve a rich visual format than a 
manual that may contain some screenshots, at most.

Best...

-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Comment by x-ji** [comment]
Right. But I use Sony DPT-RP1, which is 13" and only supports PDF.

**Comment by edumerco** [comment]
Then, it how does it reflow text?

-- 
eduardo mercovich

Donde se cruzan tus talentos
con las necesidades del mundo
ahí está tu vocación.

**Comment by x-ji** [comment]
I'm not sure what you mean. I edited my comment shortly after I posted it. Please take a look. A version of the PDF file of the manual for 0.99 is available at https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mu0/mu4e-manual-0.9.9.5.pdf

**Comment by x-ji** [comment]
If you're interested in how the reader DPT-RP1 works, you can certainly Google it online? It doesn't reflow text. It just displays the PDF as any other PDF reader on PC would do. However I believe this discussion is irrelevant to this repo.

**Comment by djcb** [comment]
`make pdf` in the `mu4e` directory should do the trick. I have attached a version.
[mu4e-1.1.0.pdf](https://github.com/djcb/mu/files/1935958/mu4e-1.1.0.pdf)

**Comment by x-ji** [comment]
Thanks :+1:
