### ISSUE TITLE
'Passed' flag incompatible with IMAP server

### ISSUE THREAD

**Issue by gartrog** [djcb/mu#1384]
I use mu4e with 2 contexts. One of them is synchronized through IMAP with an exchange server. Whenever I forward a message, I get issues when trying to synchronize the change of flags for it:

```
IMAP command 'UID STORE 910011 +FLAGS.SILENT ($Forwarded)' returned an error: BAD Command Argument Error. 11
```

It seems that this particular IMAP server does not understand the Passed 'P' flag, which indeed does not seem to be a standard flag as defined in
https://tools.ietf.org/html/rfc2060#page-9

How could I achieve not adding the 'P' flagged on forwarded messages for this particular context ? (forwarding with my second context works like a charm)

**Comment by djcb** [comment]
This is not really a m issue...

`mu` works on top of Maildirs (https://cr.yp.to/proto/maildir.html -- with the 'P' flag) and is not really concerned with synchronizing those with remote servers (IMAP or otherwise), although `mu4e` can call some external tools to do that for you.

So, what you're seeing is that some external tool (perhaps offlineimap, mbsync or whatever you are using) is mapping the Maildir to IMAP, and this particular IMAP-server has some issues with the details of that. So, I guess what you could do is check the external tool you are using for an option to do that.

E.g. https://imapsync.lamiral.info/FAQ.d/FAQ.Flags.txt describes how to do it for imapsync; there might be something similar for what you are using.

**Comment by gartrog** [comment]
Thanks a lot for the super fast and comprehensive answer.

It is indeed more an issue of the synchronization software (mbsync in this case). I will investigate in this direction.

Closing this issue.
