### ISSUE TITLE
mu4e doesn't show mails in Inbox

### ISSUE THREAD

**Issue by Nebucatnetzer** [djcb/mu#1396]
## Expected or desired behavior

mu4e shows all the emails in the inbox

## Actual behavior

It doesn't show any messages.

## Steps to reproduce

When I'm using mu4e from the Ubuntu repositories it works like it should.
However due to the `Package html2text is obsolete!` message I tried to update to the github version.
After compiling mu and pointing Emacs to new mu4e I rebuild the mu index and opened mu4e and the Inbox gets displayed empty.
The emails are visible in mutt so I reckon the sync is working fine.

## Versions of mu, mu4e/emacs, operating system etc.

- Github version
- Emacs 26.1
- OS: Ubuntu 18.04

**Comment by djcb** [comment]
Best try the command-line tools (`mu find` etc.) first; and please be very precise and specific; right now this report isn't very useful for troubleshooting.

**Comment by Nebucatnetzer** [comment]
I'm sorry for not explaining it better.
I think it has something to with mu4e and not with mu itself. When I use mu4e from the Ubuntu repository everything works fine but when I switch to mu4e from github it doesn't show any mails in my inbox.

The mail directory is both times the same and I tried to mu4e with mu from Ubuntu and with mu from github.
However that's probably anyway irrelevant because mu is only used for searching, right?

**Comment by Chris00** [comment]
What does `mu find -n 10 maildir:/inbox` (where `/inbox` is the path under `~/Maildir` that you want to query so you should adapt it to your situation) returns?

**Comment by Nebucatnetzer** [comment]
It shows the inbox just fine. However I got it working now.
I don't know what is different today, was probably a bit too late yesterday :).
Sorry for the inconvenience.

**Comment by holocronweaver** [comment]
Since this has high SEO on Google, wanted to add that I had this issue as well and solved it (though could not root cause). All but one e-mail in my Inbox suddenly disappeared in `mu find`, but the my provider's mobile e-mail client showed the inbox as I expected it.

Manually deleting the maildir Inbox subfolder (in my case, `rm -rf ~/.mail/myemail@address.com/Inbox`) then running mail sync and mu index again (in my case, `mbsync myemail && mu index`) solved the issue.
