### ISSUE TITLE
mu4e inline images not showing

### ISSUE THREAD

**Issue by paradigmshift** [djcb/mu#142]
I've set `mu4e-view-show-images` to `t` , yet I still can't view the images inline.

Imagemagick is being called.

sending the email (inline image):
![message](https://f.cloud.github.com/assets/846449/198245/c281d500-8054-11e2-8265-92a5ed4cffbe.jpg)

receiving the email:
![message-received](https://f.cloud.github.com/assets/846449/198247/c7e278a6-8054-11e2-8a40-d498f9dd80f2.jpg)

relevant code in my .emacs:

``` common-lisp
;;;; mu4e
(add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu4e")
(when (fboundp 'imagemagick-register-types)
        (imagemagick-register-types))
(require 'mu4e)

(setq
   mu4e-maildir       "~/Mail"   ;; top-level Maildir
   mu4e-sent-messages-behavior 'delete
   mu4e-get-mail-command "email-update.sh"   ;; or fetchmail, or ...
   mu4e-update-interval 600
   message-kill-buffer-on-exit t
   mu4e-view-show-images t
   mu4e-image-max-width 800
   mu4e-html2text-command "w3m -dump -T text/html"
   w3m-command "/usr/bin/w3m"
   mu4e-view-prefer-html t
   )
```

**Comment by x-ji** [comment]
Hi, not sure if I should piggyback on this old issue. I also set the variable to `t` and in `eww` I'm able to see images normally on a website. However, I'm not able to see any images in the emails that I've downloaded (testing with a Yahoo mail account). Is there any way I can test it further and find out where the problem is?

- Arch Linux 4.14.34
- mu 1.0
- Emacs: GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2018-02-09
- Imagemagick: 7.0.7-28 Q16 x86_64 2018-03-31 

I'm not sure if it's a problem with Yahoo mail instead. But when I try to run `mu4e-show-log` it does seem to display the source URLs of images in the email.
