### ISSUE TITLE
mu4e not performing with too many Maildir folders

### ISSUE THREAD

**Issue by gnusupport** [djcb/mu#1440]
All my maildir folders are in ~/Maildir/example-user@example.com

And I have 47236 folders, as for each contact there is one folder. This makes it very easy to find conversation specific for each person.

Thus [j] jump to maildir is taking crazy long time, if it works at all. 

Just a notice, that mu4e cannot handle that. Maybe some performance can be improved upon testing on your side and finding where is the bottleneck.

**Comment by 717g301github** [comment]
Maybe some solution could be found by some index of maildir folders, so that instead of the full search of the database, I can search within the index of mailfolders, like "~/Maildir/name1@example.com" "~/Maildir/name2@example.com" "~/Maildir/name3@example.com" and so on. As [j] jump to Maildir should not take long even with 42000 Maildir folders. And then I could choose Mailfolder and then enter into the conversation by using full search. This is just an idea.

**Comment by djcb** [comment]
There's `mu4e-cache-maildir-list`, does that help?

**Comment by gnusupport** [comment]
* Dirk-Jan C. Binnema <notifications@github.com> [2020-02-27 02:27]:
> There's `mu4e-cache-maildir-list`, does that help?

That would mean that I have to run it once at least. I have waited for
hours and hours, I think one time was even one day, and it never
finished its job.

Good option would be to simply give the paths of maildirs to visit, so
I did configure some of them after option [j], but option [o] is not
working for me.

Jean

**Comment by djcb** [comment]
Hmm... then I guess jump-to-maildir won't work well for you. Could it be made faster? Probably.. but this is a kind of uncommon / extreme scenario, so I'm not sure how much time / complexity we should spend on that (since our time is quite limited)

An alternative of course is to not use so many folders, after all mu/mu4e don't really care about the folders so much, and you can simply search for the messages from name2@example.com, wherever they live.

**Comment by gnusupport** [comment]
* Dirk-Jan C. Binnema <notifications@github.com> [2020-03-28 15:45]:
> Hmm... then I guess jump-to-maildir won't work well for you. Could it be made faster? Probably.. but this is a kind of uncommon / extreme scenario, so I'm not sure how much time / complexity we should spend on that (since our time is quite limited)
> 
> An alternative of course is to not use so many folders, after all mu/mu4e don't really care about the folders so much, and you can simply search for the messages from name2@example.com, wherever they live.

Alternative is when there is not so many emails.

My example is showing that mu4e is not scalable enough. Good for you,
but not good for me, as I reached the point of having too many
emails.

For each conversation with somebody@example.com I have maildir named
~/Maildir/somebody@example.com

Let's say I wish to see the conversation of that person, I simply run
it on that folder, all conversation comes fast without waiting for
long searches. That is advantage to me.

Does such option exist in mu4e, to simply open up certain mail folder?

I have just been testing it, if I wish to open the Maildir folder with
88 emails related to single email address, it takes me 1 second with
mutt, and like 3 seconds with the maildir.el package that I still use,
even it is buggy.

If I wish to open or find same email address with mu4e, it takes
longer than 30 seconds, I did not even want to wait.

Jean

**Comment by djcb** [comment]
Note, `mu` is just querying a database, it doesn't care how you separate things in maildirs; it can also just search by the from-address, no need manually make folder for that. So, you're not 'opening a maildir folder', you're querying messages, perhaps using the folder the folder they live in.

mu4e's jump-to-maildir can be slow when you have a large number of maildirs, because it tries to complete them; but that has nothing to do with the database / querying.

So, in mu4e, you'd just use a query (or make a bookmark) for `from:name@example.com`. and that is very quick.

**Comment by gnusupport** [comment]
* Dirk-Jan C. Binnema <notifications@github.com> [2020-03-28 19:06]:
> Note, `mu` is just querying a database, it doesn't care how you separate things in maildirs; it can also just search by the from-address, no need manually make folder for that. So, you're not 'opening a maildir folder', you're querying messages, perhaps using the folder the folder they live in.
> 
> mu4e's jump-to-maildir can be slow when you have a large number of maildirs, because it tries to complete them; but that has nothing to do with the database / querying.
> 
> So, in mu4e, you'd just use a query (or make a bookmark) for `from:name@example.com`. and that is very quick.

Yes, thank you.

Do you know that Emacs is lacking good access to maildirs, so I
understand that mu is for searching and indexing, but then why not
make a simple access to maildir as well?

Jean

**Comment by djcb** [comment]
We're not planning to work on this, sorry. Closing this.
