### ISSUE TITLE
mu4e shows only one draft

### ISSUE THREAD

**Issue by daphniz** [djcb/mu#1474]
## Expected or desired behavior

Jumping to the drafts folder or entering the query `maildir:/drafts`
should show the messages in `maildir/drafts/`

## Actual behavior

I see only the lastest message.  With `mu find m:/drafts` I see all.

## Steps to reproduce

Start composing a message.  Make the subject `cusp`.  Abort with `C-c
C-d`.  Look in the drafts folder.  It's there.  Now make a draft whose
subject is `apex`.  Look in the drafts folder.  Only the last is there.
Update the index.  Run `mu find m:/drafts`.  Both are there.

## Versions of mu, mu4e/emacs, operating system etc.

mu/4e: 1.3.4
emacs: 26.2
os: arch linux

## Any other detail

I don't know whether the issue might be caused by the fact that all
drafts have the same message ID, `%16 lx@fake-msgid`.

**Comment by daphniz** [comment]
I now see that setting `mu4e-headers-skip-duplicates` to `nil` solves
the problem.  Unless I'm missing something, perhaps that variable should
default to `nil` and have a warning in its docstring.

**Comment by joostkremers** [comment]
I'm experiencing the issue as well. Setting `mu4e-headers-skip-duplicates` to `nil` makes all messages visible, but IMHO it's not a good solution to the problem, because the messages are  displayed as belonging to a single thread, even though they are not. Which means, for example, that only the subject of the first message is shown.

**Comment by alexmurray** [comment]
Do the draft messages all have the same message-id? Perhaps this is the issue.

**Comment by daphniz** [comment]
@alexmurray, yes I suppose mu4e ought either to be able to distinguish
messages with the same ID or to avoid giving drafts the same ID.

**Comment by djcb** [comment]
Yes, it's probably the message-id.

`mu4e` _does_ give a message-id to draft messages, but you have to finish the editing session properly, with `message-dont-send` (`C-c C-d`), simply saving & killing the buffer is not enough.

**Comment by joostkremers** [comment]
> `mu4e` _does_ give a message-id to draft messages, but you have to finish the editing session properly, with `message-dont-send` (`C-c C-d`), simply saving & killing the buffer is not enough.

For me, the problem is complicated by the fact that I have `auto-save-visited-mode` on, which auto-saves buffers to the file they are visiting, instead of creating special auto-save  files (with `#...#`). Plus the fact that I sometimes just forget that I'm writing a message...

Wouldn't it be possible to make `mu4e` somewhat more forgiving of absent-mindedness by utilizing `{before|after}-save-hook` and possibly also `kill-buffer-hook` or `kill-buffer-query-functions`, to make sure drafts are saved correctly?

**Comment by djcb** [comment]
Yeah, that should be possible. In fact, I think the behavior _was_ like that at some point, not quite sure what changed.

**Comment by djcb** [comment]
We're generating message-id's earlier now, , so all the drafts should show up now, even when merely saving them.
