### ISSUE TITLE
Search string returning one entry at a time in mu4e

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1495]
## Behavior (expected vs actual)
I am searching for `maildir:/.*Drafts/ NOT flag:trashed` in mu4e and I am getting a single message in mu4e-headers even though I know I have 6 message in drafts that are not trashed.

**UPDATE:** The same thing happens with `maildir:/gmail/Drafts/` but not with `maildir:/gmail/Inbox/` 

If I delete that message and run the search again, I get the next message.

Also, if run 
```mu find "maildir:/.*Drafts/ NOT flag:trashed" ```
in the terminal, I get all 6 messages.

I traced the command that is being sent to mu and it seems to be

```
"cmd:find query:bWFpbGRpcjovLipEcmFmdHMvIE5PVCBmbGFnOnRyYXNoZWQ= threads:false sortfield:date reverse:true maxnum:-1 skip-dups:true include-related:false"
```

I don't know how to execute this command in mu to test the output. Any help is appreciated.

## Versions of mu, mu4e/emacs, operating system etc.
OS: CentOS 7
mu version 1.3.4
emacs version 26.2

**Comment by djcb** [comment]
This is because (by default, and unlike mu) mu4e does _not_ show multiple messages with the same message-id. And the drafts folder can easily get multiple messages with the same message id when they are not properly. saved...

...until the recent fix for #1474 -- which makes mu4e a bit more forgiving in that case.
