### ISSUE TITLE
mu: the database is empty (19)

### ISSUE THREAD

**Issue by ianbarton** [djcb/mu#1538]
I expect that this is a user configuration error, but I can't work out what the problem is! I have three computers all running ArchLinux using the same version of Emacs and mu with the same configuration (.mbsyncrc) files. On two computers my setup works correctly.

However, one the following happens:
`
dell ~ » mu index                                                                                                                                        19 ↵
indexing messages under /home/ian/mbsync [/home/ian/.mu/xapian]
- processing mail; processed: 16125; updated/new: 16125, cleaned-up: 0[1]    10090 killed     mu index
dell ~ » mu find amazon                                                                                                                                 137 ↵
database is empty; try 'mu index'
mu: the database is empty (19)
`
Email has been downloaded OK:

`
ls -la ~/mbsync
drwxr-xr-x 13 ian ian 4096 Jan  4 13:57 .
drwxr-xr-x 93 ian ian 4096 Jan  4 16:12 ..
drwxr-xr-x  2 ian ian 4096 Jan  4 13:57 cur
drwxr-xr-x  5 ian ian 4096 Dec 27 09:45 .Drafts
drwx------  5 ian ian 4096 Jan  1 22:35 INBOX
drwx------  5 ian ian 4096 Jan  4 13:39 INBOX.Archive.2016
drwx------  5 ian ian 4096 Jan  1 22:35 INBOX.Archive.2017
drwx------  5 ian ian 4096 Jan  1 22:35 INBOX.Archive.2018
drwx------  5 ian ian 4096 Jan  1 22:35 INBOX.Archive.2019
drwx------  5 ian ian 4096 Jan  1 22:35 INBOX.Sent
drwxr-xr-x  2 ian ian 4096 Jan  4 13:57 new
drwxr-xr-x  2 ian ian 4096 Jan  4 13:57 tmp
drwxr-xr-x  5 ian ian 4096 Dec 27 09:45 .Trash

`

## Expected or desired behavior

Please describe the behavior you expected / want

## Actual behavior

Please describe the behavior you are actually seeing. 

For bug-reports, if applicable, include error messages, emacs stack
traces etc. Try to be as specific as possible - when do you see this
happening? Does it happen always?  Sometimes? How often?

## Steps to reproduce

For bug-reports, please describe in as much details as possible how
one can reproduce the problem*.

**Comment by thierryvolpiatto** [comment]
Similar error here, must have to revert to 1.3.5, will try to bisect ASAP.

**Comment by djcb** [comment]
That's weird... I see there's a `[1] 10090 killed` in the log. Do you know what that is? If that's `mu` that's being killed that would explain.

**Comment by thierryvolpiatto** [comment]
I am not sure my issue here is related to this issue, but it may.
The problem here comes from the mu4e-contexts, I have a warning saying `make-mu4e-context` is unavailable, this since 0bc2e605.  This commit is not building, then you added the missing file in 384fcc5d and it then build fine, but from this commit mu is not working anymore because contexts are no more availables, also I see many bookmarks are broken, of course because of contexts broken, updating is not working anymore.
Hope that help.

**Comment by thierryvolpiatto** [comment]
So to resume the last working commit is at dcb3025d.

**Comment by djcb** [comment]
Thanks for looking into this.

I can't reproduce it, unfortunately. And note that the mu4e problems cannot explain the command-line problem. Perhaps for the mu4e issue, `./autogen.sh` first might clear up some stale files?

To look at that problem first, does `mu index` run & complete successfully? Anything interesting in `~/.cache/mu/mu.log`?

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> Thanks for looking into this.
>
> I can't reproduce it, unfortunately.

Ok, I found what's happening, don't think it's a bug, but just an
incompatible change with a possible user configuration that works since
always. Modifying my use-package call for mu4e fixed the problem.
In commit "0bc2e605 * mu4e: clean up org-handling" you moved/changed
some require calls and now we have to load mu4e differently (basically
mu4e have to be required before attempting any configuration).
Also I see `mu4e-contexts` is now a badly defined defcustom with no
:type definition (I will submit a PR soon).

> And note that the mu4e problems cannot explain the command-line
> problem.

This is why I said my issue is maybe not related with this one.

> Perhaps for the mu4e issue, ./autogen.sh first might clear up some
> stale files?
>
> To look at that problem first, does mu index run & complete
> successfully? Anything interesting in ~/.cache/mu/mu.log?

For some reasons I have nothing in mu.log since July 2019, but I guess
this is another issue unrelated with this one.

>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by djcb** [comment]
Okay, thanks. Guess there's not more to do here then..
