### ISSUE TITLE
Can't open .eml attachments

### ISSUE THREAD

**Issue by JonathanReeve** [djcb/mu#1590]
## Expected or desired behavior

I'd like an easy way to open and read .eml attachments. 

## Actual behavior

I open an email that only has an .eml attachment (do some forwarded emails work this way?), and I can't find a way to view the attachment, at least in a way that looks nice. I can run Action on attachment -> in-emacs, and select the first attachment, but then it is only treated as a Fundamental file, and I have to scroll through several pages of header stuff before I can read the email. I can try to manually enable `mu4e-view` mode, but that doesn't seem to work. 

## Steps to reproduce

1. Try to open an .eml attachment
2. Notice it isn't formatted correctly

## Versions of mu, mu4e/emacs, operating system etc.

mu --version
mu (mail indexer/searcher) version 1.2.0

Mu4e:
    Version: 20200218.546
     Commit: 151d5d9e0dd5e8e8c775035203d3e17538151f33

OS: NixOS unstable

**Comment by djcb** [comment]
This is implemented with new gnus-based message-view:
   `(setq mu4e-view-use-gnus t)`
(it's still in beta, but works quite well).

**Comment by JonathanReeve** [comment]
@djcb, does `H` for toggling between text and HTML mode not work with that enabled? For some reason I'm suddenly getting lots of HTML mail that looks really ugly with that switch turned on.

**Comment by JonathanReeve** [comment]
I'm thinking that this issue should be reopened, since the `mu4e-view-use-gnus` feature is not enabled by default and labeled as experimental. But more importantly, it creates more problems than it solves: the existing mu4e tools for downloading attachments, toggling HTML views, and so on, don't seem to work in that new view mode.

**Comment by djcb** [comment]
It'd be a pain to implement with the old interface, and this is one of the reasons why we're (slowly) moving to the gnus interface. So, embedded messages like the eml ones won't ever be implemented for the non-gnus interface, sorry!

You get many new things, some things work a little different, and there are few things missing still; but in general, I think it's much better.

**Comment by JonathanReeve** [comment]
Is there a way to toggle between plain text and html in the new interface? I used to be able to press `H` to read the plain text, but now I'm just stuck with ugly and unreadable HTML mail.

**Comment by Chris00** [comment]
On 28 February 2020 at 19:01 CET, Jonathan Reeve <notifications@github.com> wrote:
>
> Is there a way to toggle between plain text and html in the new interface? I used to be able to press H to read the plain text, but now I'm just stuck with ugly and unreadable HTML mail.

Could you be more precise what is the problem with HTML emails?  With the shr renderer, these display mostly fine.  If it is because lines stay with lots of spaces at the end, use (as I do):

(define-advice mm-shr (:around (oldfn &rest handle) delete-trailing-whitespace)
  "Delete leading and trailing whitespace in Gnus article buffer."
  (if (derived-mode-p 'gnus-article-mode)
      (save-restriction
        (narrow-to-region (point) (point))
        (apply oldfn handle)
        (delete-trailing-whitespace))
    (apply oldfn handle)))

**Comment by JonathanReeve** [comment]
So many problems with HTML mail. I'll often get HTML mail that has hard-coded text colors, so for instance an email which hard-codes a white background, and then shr displays that as black and white lines, since I'm using a dark theme. Also I'll get HTML mail that seems to have gray text displayed on gray background, so it's just unreadable: 

![Ekrankopio de 2020-02-29 16-10-20](https://user-images.githubusercontent.com/1843676/75615127-07fe5680-5b0e-11ea-82aa-e1d6a037a7ef.png)

Not to mention, any image is usually displayed at 1000% of its original size, to the point where I'm only seeing the leftmost 20% of the image, because the rest is cut off.

With this experimental feature turned off, I can just press `H` to get the plain text version, which is actually readable.

**Comment by djcb** [comment]
gnus-mode will get toggle functionality as well, but for now you could use e.g.
```
(add-to-list 'gnus-buttonized-mime-types "multipart/alternative")
```
which wil then let you choose between the alternatives.

**Comment by theophilusx** [comment]
There does not appear to be a simple 'toggle' for switching between
plain text and HTML views in gnus or a variable to control when to
prefer plain text version over HTML. However, gnus is a bit of a monster
and I'm not that familiar with it, so it can probably be tweaked to
better suit your preferences, but that detail is beyond my knowledge.

My default gnus settings do result in the plain text version of the message
being included as an attachment in the header display - clicking on that
attachment does open the plain text version of the message.

You can improve the HTML rendering by adjusting some of the settings for
shr, either via M-x customize-group <ret> shr or by setting the
appropriate variable in your emacs init file. From what you have posted,
I suspect this would address the majority of your issues with HTML views
of your email.

Some variables to look at might be

- shr-max-image-proportion - for your image size issue
- shr-use-colors - on by default. Turn off to stop shr using the colors
  specified in HTML
- shr-use-fonts - turn off to stop shr trying to honour HTML/CSS
  specified fonts.

In addition to the above, there is also a group called shr-colors which
contains variables

- shr-color-visible-distance-min - minimum distance between two colors
  for them to be considered visible

- shr-color-visible-luminance-min - as above but based on luminance

Getting the above to an appropriate value will likely allow you to
honour color settings in the HTML, but still have the result be visible
given your dark theme. I also use a dark theme, but getting the above
settings 'just right' seems to be a bit of a black art which I've never
managed to get quite right. However, I'm happy to turn off colour
requests in renedered HTML anyway.

It is fairly clear that adding some of the features being requested by
users to the old message view module has become difficult and/or
unmaintainable, hence the move to leverage off the gnus infrastructure
to provide this functionality. This integration is a little complex due
to the extent of functionality provided by gnus and I suspect it will
take a bit of time before some of the features provided by gnus become
accessible/usable in mu4e. I've been using the gnus based view since it
was first released and have noticed significant improvements since it
was first introduced.

The ability to easily switch between HTML and plain text view would be
very useful and I would like to have a setting similar to
mu4e-view-html-plaintext-ratio-heuristic for tweaking when gnus uses
HTML or plain text rendering.

My personal preference is for plain text. Having HTML email is one of
the worst things that ever happened to email IMO. Unfortunately, there
seems to be a growing number of email agents and applications that don't
send RFC compliant messages e.g. no plain text part or a plain text part
that does not provide a plain text version of the message. Like the VHS v
Beta battle, I think HTML has won email dominance. Therefore, we are
probably better off working out how to make HTML rendered messages work
well rather than reverting to plain text.

Jonathan Reeve <notifications@github.com> writes:

> So many problems with HTML mail. I'll often get HTML mail that has hard-coded text colors, so for instance an email which hard-codes a white background, and then shr displays that as black and white lines, since I'm using a dark theme. Also I'll get HTML mail that seems to have gray text displayed on gray background, so it's just unreadable:
>
> ![Ekrankopio de 2020-02-29 16-10-20](https://user-images.githubusercontent.com/1843676/75615127-07fe5680-5b0e-11ea-82aa-e1d6a037a7ef.png)
>
> Not to mention, any image is usually displayed at 1000% of its original size, to the point where I'm only seeing the leftmost 20% of the image, because the rest is cut off.
>
> With this experimental feature turned off, I can just press `H` to get the plain text version, which is actually readable.


--
Tim Cross

**Comment by djcb** [comment]
There's `mm-discouraged-alternatives`, guess we can use that to implement the toggle.

And as mentioned `(add-to-list 'gnus-buttonized-mime-types "multipart/alternative")` gives you the toggle right now, add the cost of seeing 
```
1.  ( ) text/plain          (*) text/html           
```
at the top of messages.

**Comment by Chris00** [comment]
On 29 February 2020 at 22:13 CET, Jonathan Reeve <notifications@github.com> wrote:
>
> So many problems with HTML mail. I'll often get HTML mail that has hard-coded text colors, so for instance an email which hard-codes a white background, and then shr displays that as black and white lines, since I'm using a dark theme. Also I'll get HTML mail that seems to have gray text displayed on gray background, so it's just unreadable:

Is your image with the Gnus viewer or the default one?  If you use `shr` to render HTML and your background color is stored in, say, `background-color`, you may want to do

(define-advice shr-colorize-region (:filter-args (r) default-bg-color)
  "Use the default background color if close."
  (list (car r) (cadr r) (caddr r) my-background-color))

You may also want to experiment with `shr-color-visible-luminance-min`.

Alternatively instead of (setq mm-text-html-renderer 'shr) specify another renderer such as `w3m-standalone` which will remove all colors.
