### ISSUE TITLE
Displaying again a message with a mark erases the mark

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#1744]
## Expected or desired behavior

When displaying again a message with a mark (trash, move), leave the mark on the message.

## Actual behavior

At the moment, when one redisplays a message with a mark, the mark is removed.

## Steps to reproduce
Put the trash mark on a message and redisplay it.

## Versions of mu, mu4e/emacs, operating system etc.

Mu dev (commit 31f918ea)
Emacs 26.3 on Debian GNU/Linux

**Comment by haji-ali** [comment]
This is also related to an issue I reported (#1736). Both issues are caused by the behaviour that the message header is removed and then reinserted when a message is opened.

If the only reason for this behaviour is updating the face of a read message, then perhaps setting the face of a message header rather than removing it from the header list would be enough and would resolve the current issue (and #1736).

**Comment by djcb** [comment]
This is a very old issue, #474. That doesn't fix it of course but I'll try to do something about this during 1.5.x.
