### ISSUE TITLE
Decrypting mails much slower in "normal" mu4e-view than with mu4e-view-use-gnus

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#1793]
## Expected or desired behavior

It would be great to have this as fast as with mu4e-view-use-gnus, I am actually using mu4e-view-use-gnus only for this feature i.e. having decryption faster than with normal mu4e.

## Actual behavior

Take about 1s to 2s more than with mu4e-view-use-gnus.

**Comment by nils-schween** [comment]
Hi everyone,

since this is a recurring issue, I would like to make a suggestion concerning the principal strategy to deal with encrypted emails. But first of all a small collection of the issues and the mailing list posts related to this unpleasant behaviour of mu:

https://github.com/djcb/mu/issues/1536
https://github.com/djcb/mu/issues/1733
https://github.com/djcb/mu/issues/1652
https://groups.google.com/g/mu-discuss/c/XuxZqvdvA9Q/m/IdSfhh1bAgAJ

My idea is to decouple the encryption process and interpretation of the signatures from the actual opening of an email. When mu is started, an instance of mu-server starts and handles the requests send to it by mu4e. Instead of decrypting an email, when it is read, the mu-server could do this asynchronously for all emails in the background and it can cache the content in the xapian database. Therefore it would ask, the moment it starts, only once for the password of your gpg key. Next to the advantage of accelerating the process of opening encrypted and signed emails, it fits better into the overall concept of mu: mu is an email tool which is based on a fast search algorithm. But it cannot search the body of encrypted emails. Thus, in case a user only writes and receives encrypted emails (hopefully the future), he cannot use mu as it was designed. 

Of course the two advantages, i.e. acceleration and the option to search, come at a cost: At least while mu-server is running, the content of the encrypted emails would be stored unencrypted. Maybe this is avoidable while still allowing for searching it, if the content was hashed. This is comparable to an encrypted home partition: Once you are logged in, everything is unencrypted as a long as the session takes.  And of course, a mechanism to clean the cache, once mu-server stops is needed. 
And for the long term development perspective it is important if this change is compatible with emacs tools like the gnus reader and emacs auth-source to handle the mu-server session taking care of decrypting mails.

Maybe it would be good to implement all this in a way that it can be turned on or off, because some people may prefer that there emails are decrypted, when read. I was thinking of an additional option when mu init is called. 

I think there is still a lot to worry about. I just wanted to start the discussion.

**Comment by djcb** [comment]
Mu is not going to keep around unencrypted mail, but you can use gpg-agent to avoid having to giving your password each time. And I would recommend using the the gnus-based message-view, which avoid most of these issues.

**Comment by nils-schween** [comment]
@djcb thank you for your reply. I agree that it is not very elegant to store the content of decrypted mails in the xapian database. And I noticed that everything related to encryption becomes faster if gnus is used. But nonetheless, the main problem adresed in my previous post is that it is not possible to search the body of encrypted emails and mu is a search based email tool. 

In the last years more and more parts of the internet were encrypted, e.g. every website now has a tls certificate or almost all messengers on a smartphone use p2p encryption, I personally hope that this development does not stop and that, eventually, we will also encrypt our email communication.

I am not an expert, but I think that there are some tools like e.g. borg backup which use hashing algorithms to make searching of encrypted content possible.

It would be nice if we could go on discussing this.

**Comment by djcb** [comment]
You can batch-decrypt your mail using a bit of shell-scripting, and use that with mu4e... but since it's fundamentally risky, I don't want to do that directly with mu/mu4e; small bugs could suddenly be critical security issues, really not something I want to deal with.
