### ISSUE TITLE
Needs to run mu4e-update-index manually after each update

### ISSUE THREAD

**Issue by thierryvolpiatto** [djcb/mu#1815]
## Expected or desired behavior

Can read my unread emails after update or any bookmark e.g. today bookmarks, without having to run mu index manually.

## Actual behavior

After hitting "U" (mu4e-update-mail-and-index) in main-view, I see in the main view buffer that I have unread emails bookmarked but after hitting "b u" (bookmark unread mails) mu find nothing, I have to either kill the mu4e process and restart mu or run M-x `mu4e-update-index`. running mu index from a shell works as well.
This is happening since I have changed my Email provider (posteo) and all my emails are encrypted.

## Steps to reproduce

Probably need to have all emails encrypted but I am unsure.

## Versions of mu, mu4e/emacs, operating system etc.

Last mu from git (master) emacs-27, I use the gnus view as well, but the bug is reproductible with normal view as well.

## Any other detail

No other details for now.

Thanks.

**Comment by djcb** [comment]
Note that that bookmark counts in the main-view do _not_ exclude messages no longer in the file system, nor does it exclude duplicate messages (both for speed-reasons).

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> Note that that bookmark counts in the main-view do not exclude
> messages no longer in the file system, nor does it exclude duplicate
> messages (both for speed-reasons).

Yes, but it is not the case here.



-- 
Thierry

**Comment by djcb** [comment]
So it seems the index is not automatically updated (since doing it manually fixes the problem). Perhaps the retrieval finished with a non-zero exit code?

That still doesn't explain why the new messages would be indicated in the main-view though. Puzzling.

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> So it seems the index is not automatically updated (since doing it
> manually fixes the problem). Perhaps the retrieval finished with a
> non-zero exit code?

No process ends properly.

> That still doesn't explain why the new messages would be indicated in
> the main-view though. Puzzling.

Yes don't understand what's going on for now.

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

**Comment by lane-brain** [comment]
I'd like to say that I am also having this issue, I have to close emacs to have my shell do mu index after my mbsync update. I believe that I used to have it working at some point. I now have a new config after switching to doom emacs, though I don't know whether it it was working before or after because most of my final config came together I made the switch (aka, I started a new config shortly after beginning to try out mu4e). I have four contexts defined, so I wonder if it could be related at all to that, as otherwise my config options for mu4e are pretty tame.

**Comment by thierryvolpiatto** [comment]
Lane <notifications@github.com> writes:

> I'd like to say that I am also having this issue, I have to close
> emacs to have my shell do mu index after my mbsync update. I believe
> that I used to have it working at some point. I now have a new config
> after switching to doom emacs, though I don't know whether it it was
> working before or after because most of my final config came together
> I made the switch (aka, I started a new config shortly after beginning
> to try out mu4e). I have four contexts defined, so I wonder if it
> could be related at all to that, as otherwise my config options for
> mu4e are pretty tame.

I finally made it working by cleaning up my mail directory, reindexing,
and I reverted from my config `mu4e-index-lazy-check` to default value
(just removed it).

-- 
Thierry

**Comment by lane-brain** [comment]
when you say clean up, what exactly do you mean?

**Comment by thierryvolpiatto** [comment]
Lane <notifications@github.com> writes:

> when you say clean up, what exactly do you mean?

Fetch emails from a new directory with offlineimap.

-- 
Thierry

**Comment by lane-brain** [comment]
After starting a new maildir directory, repulling all my mail and starting a new mu db I didn't have the same luck.

I've been investigating this, tidying up my mu4e config as much as possible and still no luck. I've found a perplexing error in mu4e-alert-logs that I feel as if it might be related to this current situation:

`Failed to execute a queued callback because: %sSymbol’s value as variable is void: mu4e~main-buffer-name`

FWIW I have also had the problem that no maildirs show up in my maildirs list, which I'm not sure is related or not. Currently I am pulling from four different accounts that are each in subdirectories under ~/.mail, and I have contexts defined for each.

**Comment by djcb** [comment]
@thierryvolpiatto: Ah, so then it seems the listings in the main-view were somewhat of a red-herring. Guess we should add a note in the FAQ about this for mbsync.

**Comment by lane-brain** [comment]
The reinitialization of the maildir didn't do it for me, but I found that doom emacs was switching on the lazy check and fast cleanup options. Setting them back to the default values fixed it up; for any doom heads who are browsing this thread:

`;; Revert Doom-emacs fast index settings back to default
(with-eval-after-load 'mu4e
  (setq
    mu4e-index-cleanup t      ;; do a full cleanup check
    mu4e-index-lazy-check nil))    ;; consider up-to-date dirs`

**Comment by averter** [comment]
Just a note @lane-brain . I've recently solved the exact same issue as you, but mbsync worked fine even with `mu4e-index-lazy-check` set to `t`. According to the documentation you might loose quite some speed if you leave it as `nil` (just thought I should share this info).

**Comment by lane-brain** [comment]
ty for the tip! thankfully the update isn't really slow for me with lazy-check set to nil

**Comment by ptoal** [comment]
I have been having this exact issue, and just recently discovered that the value was set by doom emacs.  I have been trying a ton of different combinations, lately, to see which approach I like best (mbsync, offlineimap, IMAP vs. Labels, etc).

I have settled on using Gmail Labels, because that's a native way of implementing the workflow I'm looking for (Basically, the famous Magnus Therning approach).  That eliminated mbsync, as it has no native support for GMail's labels.

The (mu4e +gmail) option enables an opinionated set of configurations that are not working with this setup.  
https://github.com/hlissner/doom-emacs/blob/1255ebdbd7f0d934bc44aa10b74ff95033240221/modules/email/mu4e/config.el#L120

What I've done is remove all the conflicting config from my .doom.d/config.el file, point all the folders (draft,sent, etc) to my [Gmail].All Mail folder, and try running with the Doom settings.

So far, so good.

**Comment by djcb** [comment]
Okay, thanks. Closing this.
