### ISSUE TITLE
Allow mu-init to accept multiple maildir locations via multiple -m's

### ISSUE THREAD

**Issue by derekschrock** [djcb/mu#1820]
## Expected or desired behavior

mu-init to accept multiple -m locations, display them with mu-info, and index over all locations via mu-index

## Actual behavior 

Before 1.4.x you could index multiple maildir locations via mu-index and -m.  With 1.4.x mu-init will only use the last -m location provided.

## Steps to reproduce

mu init -m /path/to/maildir1 -m /anotherpath/to/maildir2
mu info
...
schema-version     : 451
created            : Wed Oct 21 18:56:00 2020
maildir             :  /anotherpath/to/maildir2
...

mu index    # indexs /anotherpath/to/maildir2

## Versions of mu, mu4e/emacs, operating system etc.

1.4.13, n/a, FreeBSD 12.1

**Comment by djcb** [comment]
Even in the 1.2 days having multiple maildir-roots in one database wasn't really supported, since it can lead to inconsistencies (many things work in terms of relative maildirs, e.g. `/foo` could be either `Maildir1/foo` vs `Maildir2/foo`). 1.4 explicitly enforces this;  it also simplifies some other things.... so multiple root maildirs aren't coming back.

But, you have some options:
- stay at 1.2
- use separate databases for each maildir
- move all maildirs under one toplevel
- use symlink / bind mounts under the one top level (but this requires mu >= 1.5.x, i.e. the development version)

**Comment by schoettl** [comment]
Nice! I missed the update to 1.5 but now this setup with Thunderbird seem to work:

```
$ mkdir ~/Maildir
$ ln -s ~/.thunderbird/xxx.maildir/Mail/ ~/Maildir/local
$ ln -s ~/.thunderbird/xxx.maildir/ImapMail/ ~/Maildir/imap
```
I use Thunderbird to sync mails (the setting to use maildir instead of mbox must be enabled). This way, I have the additional power of `mu find` …

Not sure yet, if I can also use mu4e to edit the maildir because Thunderbird has it's own index in `.msf` files which may not be updated if the maildir is edited from the outside. But read-only should work.
