### ISSUE TITLE
mu4e-org-store-and-capture broken

### ISSUE THREAD

**Issue by dochego** [djcb/mu#1840]
## Expected or desired behavior

calling mu4e-org-store-and-capture on a message opens a dialogue to create a corresponding todo item

## Actual behavior

No dialog to create todo item is opened.

Error message (in *Message* buffer):
user-error: No method for storing a link from this buffer

## Steps to reproduce

call mu4e-org-store-and-capture on a message, either in message or header view

## Versions of mu, mu4e/emacs, operating system etc.

emacs 27.1
mu4e after commit 13118ae173b5adeff9bc812d16e52163235468a6  (fixing issue #1829) has this issue.

mu4e before this commit behaves as expected

**Comment by theophilusx** [comment]
I"m seeing the same bug. My capture templates no longer work in mu4e messages. Previously, the following capture template would work , but since the above mentioned commit, it stopped working. 

````
("m" "mail" entry
         (file+headline "~/Documents/org-data/refile.org" "Comms")
         "* Mail: %? from %:from \n\n  Subject %:subject\n\n   %i\n  %a"
         :empty-lines-after 1)
````

None of the template expansions work i.e. %:from %:subject %a etc
Reverting to the commit just prior to the one mentioned by @dochego also fixed it for me.
