### ISSUE TITLE
Automatically mark as read when refiling

### ISSUE THREAD

**Issue by mwip** [djcb/mu#1890]
## Expected or desired behavior

When I refile an email, it would be nice if it would be marked as read automatically. Otherwise I would have to go to the archive and manually mark it read. 

## Actual behavior

Refiled messages are not marked as read automatically.

## Steps to reproduce

Refile an unread email from e.g. your inbox. It will be refiled, but still be unread.

## Versions of mu, mu4e/emacs, operating system etc.
OS: Arch Linux; Kernel 5.10.5-arch1-1
mu version 1.4.14
Emacs 27.1

**Comment by djcb** [comment]
Hmmm, I prefer the current behavior, so I'm afraid that's not going to change.

**Comment by pedrormjunior** [comment]
Is there a way to define a custom option for this? It is quite annoying to have the message you are just reading still marked as unread...

**Comment by djcb** [comment]
When you read a message, it's marked as read. I'm guessing you may be getting _copies_ of that message when you sync with gmail / similar services.

**Comment by pedrormjunior** [comment]
Any intuition on how to solve this? It seems this undesired behavior was introduced by mu4e at some point. As I remember, some months ago everything was working as expected. After I did a pull (with many new commits, as I've not been updating often) on the local code, also some months ago, this behavior had been introduced. Later I did some more updates (many new commits again) hoping the "bug" had been fixed but never did (that's why I was asking about possible custom options).

I just thought on trying to track the commit that introduced this undesired behavior, but it is something slow to test, as I would need to send emails to myself or wait for a new mail to arrive just for checking the behavior.

Any idea of what is causing this behavior? Any part of the code that may be responsible for this behavior? I'm willing to put may hand on the code to solve this, just let me know were I could find it, if you know.

**Comment by djcb** [comment]
You mentioned using 1.4.x, which is the stable release, and it hasn't received any non-trivial changes for quite some time. Like I said, I suspect it might be some artifact of an imap-syncing program, so I'd start there.

**Comment by djcb** [comment]
(oh, the original report mentioned 1.4.x, so perhaps that does not apply; the sync part does though)

**Comment by mwip** [comment]
I investigated the issue a bit further. As @pedrormjunior already pointed out, and indeed this is what confused me in the first place, this behavior is only to be found in mu(4e). I tested thunderbird on the same machine for reference, no problems there.

Let me re-describe the issue: I have an email. As you pointed out, once opened, the mail is marked as read. Upon refiling the mail is moved to the archive folder. There it is also read. However, once the mailbox is synced, the message is marked as unread in the archive. As @djcb suggests, it seems that, at some point, the message is interpreted as new by mbsync/imap/...

I use the ProtonMail bridge and mbsync, maybe this is relevant? I'd be happy to provide any logs, if you could give me a hint what might be useful.

**Comment by mwip** [comment]
One thing to add, still: 

When marking a message as read, triggering a mailbox sync, then refiling the message and triggering the mb sync again, the message is refiled and marked as read. 

That is, it seems that mbsync somehow gets confused when having to change both the properties "read" and "folder".
