### ISSUE TITLE
Request/offer to include docs on gmail, mbsync, trash delete in configuration docs

### ISSUE THREAD

**Issue by emin63** [djcb/mu#1935]
## Expected or desired behavior

It would be great if the documentation at https://www.djcbsoftware.nl/code/mu/mu4e/Gmail-configuration.html included configuration hints for mbsync

## Actual behavior

The documentation at https://www.djcbsoftware.nl/code/mu/mu4e/Gmail-configuration.html provides a sample for offlineimap but not mbsync.

## Any other detail

First, thanks for mu and mu4e. These are great. After a long hiatus I tried to get these working and ran into problems where local deletes (with either `d`, `D`, or `m t` in mu4e) did not propagate to gmail when using mbsync. There are many scattered comments on this in blogs, mailing lists, tickets, and so on.

After much frustration, I realized that there are at least two critical features required in configuration settings to get this working:
  1. The trash channel must come first in your `.mbsyncrc`
  2. `mu4e-change-filenames-when-moving` should be set to `'t`

Regarding the first point, something like
```
Group mymail-gmail
# VERY IMPORTANT: trash must be first
Channel mymail-gmail-trash
Channel mymail-gmail-inbox
Channel mymail-gmail-sent
Channel mymail-gmail-all
Channel mymail-gmail-starred
```
would work while the following will **NOT** work:
```
Group mymail-gmail
# VERY IMPORTANT: following won't work since trash is not first
Channel mymail-gmail-inbox
Channel mymail-gmail-sent
Channel mymail-gmail-trash
Channel mymail-gmail-all
Channel mymail-gmail-starred
```

I am by no means an expert so it would be great if someone more experienced could add those docs. If nobody is willing or available and you would be willing to consider a pull request describing the above, please let me know which documentation file I should edit.

Thanks again.

**Comment by theophilusx** [comment]
The challenge with providing an example is that there is no 'one way' to
do it. In case it helps, below are the relevant parts of my mu4e and
mbsync config.

Gmail is a little 'odd' in the sense that it does not have
real folders. There is really just one folder with an illusion of
folders based on tags. This means every 'folder' you pull down is really
pulling down duplicates of messages in the 'All Mail' folder.

It is possible my config is somewhat 'out of date' as I did read some
time ago that new functionality was being added to mbsync to make it
work better with imap servers like gmail which use tags rather than real
folders. I've not looked into this in any detail, just mention it as
there may well be far better ways to setup mbsync now (another problem
with providing an example - mbsync config is really outside scope for mu4e).

Note also I'm not sure your observation on the trash folder
coming first is correct. I don't recall running into that issue when I
bothered to have it configured. However, I also realised it was not
necessary, so don't have it configured now as I let the gmail imap
server take care of putting deleted messages in trash. I have the
following in my gmail context for my mu4e setup (I have a number of
different contexts)

 :vars
   '((user-mail-address . <my gmail address>)
     (user-full-name . <my name>)
     (mu4e-compose-signature . (concat "my signature"))
     (mu4e-drafts-folder . "/gmail/Drafts")
     (mu4e-sent-folder . "/gmail/Sent Mail")
     (mu4e-trash-folder . "/gmail/Bin")
     (mu4e-refile-folder . "/gmail/All Mail")
     (mu4e-maildir-shortcuts . (("/gmail/INBOX" . ?i)
                                ("/gmail/Sent Mail" . ?s)
                                ("/gmail/All Mail" . ?a)
                                ("/gmail/Drafts" . ?d)
                                ("/gmail/Starred" . ?f)))
     (smtpmail-smtp-server . "smtp.gmail.com")
     (smtpmail-smtp-service . 587)
     (mu4e-sent-messages-behavior . delete))

Below is an example of my mbsync config. I don't claim it is correct or good,
but it has been working well for me for a long time. I do not try to
pull down everything because with the way Gmai works (where there is
really only 1 mailbox and all messages are grouped using tags) this just
results in multiple copies of the same message. My config tries to find
a balance between convenience and duplicate messages.

# mbsyncrc based on
# http://www.ict4g.net/adolfo/notes/2014/12/27/EmacsIMAP.html

# ACCOUNT INFORMATION
IMAPAccount gmail
Host imap.gmail.com
Port 993
User <my full gmail address>
PassCmd "gpg -q --for-your-eyes-only --no-tty -d ~/.secure/gmail.gpg"
AuthMechs LOGIN
SSLType IMAPS
# below handy when debugging
# PipelineDepth 1

# REMOTE STORAGE (USE THE IMAP ACCOUNT SPECIFIED ABOVE)
IMAPStore gmail-remote
Account gmail

# LOCAL STORAGE (CREATE DIRECTORIES with mkdir -p Maildir/gmail)
MaildirStore gmail-local
Path ~/Maildir/gmail/
Inbox ~/Maildir/gmail/INBOX

# CONNECTIONS SPECIFY LINKS BETWEEN REMOTE AND LOCAL FOLDERS
#
# CONNECTIONS ARE SPECIFIED USING PATTERNS, WHICH MATCH REMOTE MAIl
# FOLDERS. SOME COMMONLY USED PATTERS INCLUDE:
#
# 1 "*" TO MATCH EVERYTHING
# 2 "!DIR" TO EXCLUDE "DIR"
# 3 "DIR" TO MATCH DIR

Channel gmail-inbox
Master :gmail-remote:
Slave :gmail-local:
Create Both
Expunge Both
SyncState *

Channel gmail-sent
Master :gmail-remote:"[Gmail]/Sent Mail"
Slave :gmail-local:"Sent Mail"
Create Both
Expunge Both
SyncState *

Channel gmail-all
Master :gmail-remote:"[Gmail]/All Mail"
Slave :gmail-local:"All Mail"
Create Both
Expunge Both
SyncState *

Channel gmail-drafts
Master :gmail-remote:"[Gmail]/Drafts"
Slave :gmail-local:"Drafts"
Create Both
Expunge Both
SyncState *

# GROUPS PUT TOGETHER CHANNELS, SO THAT WE CAN INVOKE
# MBSYNC ON A GROUP TO SYNC ALL CHANNELS
#
# FOR INSTANCE: "mbsync gmail" GETS MAIL FROM
# "gmail-inbox", "gmail-sent", and "gmail-trash"
#
Group gmail
Channel gmail-inbox
Channel gmail-sent
Channel gmail-all
Channel gmail-drafts


--
Tim Cross

**Comment by emin63** [comment]
Thank you for your kind and quick reply.

I agree with most of what you said (e.g., gmail is odd, duplicate emails, this is not the place for a thorough discussion of mbsync). The reason I asked is because many places seem to suggest using mbsync with mu4e but gmail seems to cause all kinds of strange problems and there is no clear canonical working configuration for mbsync with mu4e. If it would be possible to provide a minimal starting configuration for mbsync and mu4e, I think it could help a lot of people

I have some detailed questions and responses below.

> Note also I'm not sure your observation on the trash folder coming first is correct.

You may be right. I've seen this mentioned in various places and it seemed like it might have been the problem in my case, but now I'm less sure. Possibly it was because I had recently deleted a lot of emails in gmail and the large trash mailbox was causing sync issues.

> I don't recall running into that issue when I bothered to have it configured. However, I also realised it was not necessary, so don't have it configured now as I let the gmail imap server take care of putting deleted messages in trash. I have the following in my gmail context for my mu4e setup

`<snip>`

This is very helpful. Thank you. A few questions:

  1. I notice that you do not sync the trash folder via mbsync but you have `(mu4e-trash-folder . "/gmail/Bin")`
     - Should I not sync trash/bin?
     - Do you use `m t` to trash an email by moving it to your local trash folder or do you use `d`?
  2. You have a shortcut for starred, `("/gmail/Starred" . ?f)`, but do not sync the starred folder.
     - Won't that cause problems if you locally move something to starred? How will it sync to the server?
  3. You don't have `mu4e-change-filenames-when-moving` in your mu4e setup.
     - Various places suggest that is important if using mbsync. Do you have an opinion on that?

I agree that there are many ways to setup mu4e and mbsync. I would just like to get some minimal working config where delete/trash works. There seem to be conflicting answers at various places on the internet and so having a small canonical answer in the mu4e docs seems like it would be useful.

Thanks again.

**Comment by theophilusx** [comment]
>
> This is very helpful. Thank you. A few questions:
>
>   1. I notice that you do not sync the trash folder via mbsync but you have `(mu4e-trash-folder . "/gmail/Bin")`
>      - Should I not sync trash/bin?

it was never clear to me exactly what the relationship between the
mu4e-trash-folder and your external syncing program was, so I just left
it there (my original config was based on something I found with google)

I don't explicitly sync the trash folder

>      - Do you use `m t` to trash an email by moving it to your local trash folder or do you use `d`?

I use 'd'


>   2. You have a shortcut for starred, `("/gmail/Starred" . ?f)`, but do not sync the starred folder.
>      - Won't that cause problems if you locally move something to starred? How will it sync to the server?

I never used starred - never found a use for it or found it of any
benefit. If a message is important enough, I use org-capture and add it
to my org data with appropriate metadata. Besides, I can always find it
quickly in 'All Mail" using mu4e search. I also don't use 'Snooze" or
some of the other gmail features.

>   3. You don't have `mu4e-change-filenames-when-moving` in your mu4e setup.
>      - Various places suggest that is important if using mbsync. Do you have an opinion on that?
>

Sorry, I have that set globally, not inside a mu4e cntext definition. My
full setup is much much larger with around 8 different contexts.


> I agree that there are many ways to setup mu4e and mbsync. I would just like to get some minimal working config where delete/trash works. There seem to be conflicting answers at various places on the internet and so having a small canonical answer in the mu4e docs seems like it would be useful.
>

I don't know if there is one. That is partly my point. The reason I
provided my config as an example was primarily to show you don't need to
sync trash/bin.

I seem to be able to see deleted messages when I visit the local deleted
folder, but that is likely only messages deleted on the local machine
(I've not verified). However, I'm not worried about that because the
'Bin' folder in my Gmail account has a full record, regardless of where
the message was deleted from. This works fine for me - I don't care if
my local deleted folder is not an exact copy of the Gmail one and would
rather have the faster syncing.

As mentioned, there is no 'one way' and what I have works fine for my
needs. I read mail with multiple clients (tablet, phone, laptop,
desktop) and with multiple clients (mu4e, thunderbird, mutt, Apple
Mail). Gmail is the 'definitive' master record. Sometimes, after a mu
upgrade, I might even wipe out all local copies and re-sync from scratch
(not often as that takes a while and due to gmail limits, takes multiple
sync goes to get it all).

There are a few additional things I think I could change to make syncing
faster, but like all optimisation, you really only do it when there is a
need and for me, currently, there is no need for faster.

**Comment by lockywolf** [comment]
I agree that it would have been nice!

It would be nice to have all features working!

I am surprised that you have channels per folder. I have channels per account and `Patterns *` set.

I generally do not use Bin, but I have just tried binning one message from Gmail's web interface, and it arrived to the [Gmail]/Bin folder successfully, except kinda duplicated 1->6.  I don't care to understand why.  Three of those are hidden by mu4e, and 3 are visible in the bin. 

Then I expunged that message from gmail's web interface, synced the maildir, and it disappeared from the [Gmail]/Bin directory.
I think this is more or less what is expected.

**Comment by lockywolf** [comment]
Also, see https://github.com/djcb/mu/issues/1939

**Comment by emin63** [comment]
OK, thank you everyone for the feedback. That is helpful.

I'm still having a little trouble getting Gmail to work right with trash, delete, etc., but will review my software versions, config file, settings, and so on.

I still think it would be valuable to have a canonical document with working mbsync+mu4e config for gmail but it seems like I am in the minority and this newbie issue not of general interest so I'm closing this ticket.

Thanks.

**Comment by djcb** [comment]
Well, sure, if someone can write about `mbsync`, we can add to the documentation (in the appendices), with the various trade-offs etc., as there isn't really a "best way".
