### ISSUE TITLE
Gnus("news") setup

### ISSUE THREAD

**Issue by nils-schween** [djcb/mu#1941]
Since we are moving to Gnus("news") based message view now, I would like to ask the community to share their gnus setups. For example, I would like to know how you live without the nice shortcuts of mu4e-views? Did you write your own shortcuts? And I am also interested in knowing, if you read your news feed with gnus and your email with mu4e, or if you only use one of them. And for example, what about html emails, do you use a special setup? And do you have any other tipps for gnus?
If you we collect some nice setups, I would volunteer to write a small sections for mu4es manual.

Thanks for sharing,
Nils

**Comment by theophilusx** [comment]
For me, there was nothing I needed to change apart from setting the
variable to use gnus to view messages. No HTML config necessary and I'm
not sure what shortcuts your referring to. I just set the variable and
got faster and more reliable rendering - everything else stayed the
same.

**Comment by djcb** [comment]
Anything specific you're missing? We'll bring some more things (such as URL links), and possibly some more things.

Note, gnus assumes various things that are not necessarily true in the mu4e context, so trying to grab things from gnus-setups isn't always so easy.

**Comment by nils-schween** [comment]
Thanks for you replies. I filed this issue out of curiosity, because I wanted to find out if people had adapted their setups and if  people use both gnus and mu4e at the same time. Well, of course, I am missing the shortcuts (@theophilusx https://www.djcbsoftware.nl/code/mu/mu4e/MSGV-Keybindings.html#MSGV-Keybindings in particular, the ones under the "actions" section). But @djcb you already said, that some of them will be implemented. For example, the "extract attachment" shortcut seems to be already implemented, but when I type "e" I get the following error message: `funcall-interactively: Symbol’s value as variable is void: helm-mode` . Probably, it is because I am using ivy instead of helm. Another thing I noticed is that all signed emails have an additional "box" stating `[[PGP Signed Part: Undecided]]`. That is strange, since I have added the keys of the senders to my public key list. In mu4e-view mode, I get   `verified`. And are people now configuring their "view" mode with the variables describe in http://www.gnus.org/manual/gnus_63.html#Article-Buffer . And we will key bindings be compatible with the keybindings of gnus (i.e. the best of the two worlds). I think these are the concrete points. But as I said, it is more about a general exchange. Thanks. Nils

**Comment by theophilusx** [comment]
@nils your reference to 'shortcuts' wasn't clear. I now understand your
talking about the default key bindings. Some of these changed because of
underlying changes brought in by using gnus to view messages. (I've been
using the gnus view mode for so long, I cannot remember exactly what
changed). It isn't that the key bindings have been lost so much as there
have been changes to accommodate how gnus works. However, I've not
noticed any specific loss of functionality. Recommend you check the
current manual to see what bindings have changed (v1.4.15 or 1.5.9 for
dev version). There is some functionality which remains to be added (as
pointed out by @djcb) and I suspect there is some which is either
available in a slightly different manner or which is not compatible with
how gnus message view works that may not be re-implemented. Of course,
YMMV depending on how you use mu4e and how heavily you customized it. I
certainly have a few custom actions defined, but they all continued to
work for me. I also run the dev version (1.5.9), which I've found to be
very stable and reliable.

On my system, hitting 'e' in the message view prompts me to indicate
which attachment to save. I'm running with ivy. It could be the helm
error you are seeing is a local configuration issue. I have not done
anything specific wrt helm configuration and my ivy config is minimal.

I'm not sure about the PGP issue. I've not got any PGP signed messages
at present, so cannot check. I do recall there has been some discussion
of PGP related issues in the past, so checking old issues may provide
some pointers.

The improvements brought about by using gnus to view messages are
significant. Unless you are running a heavily customized version with
your own functions and key bindings, there is little configuraiton
change needed (if any). There are some key binding changes to get use
to, but that is about all.

I haven't used newsgroups in years. When I did read them, I did use
GNUS. I have no GNUS specific configuration in my setup.

**Comment by djcb** [comment]
For 1.6, we'll need to document the gnus-based view as well, hopefully that will help getting up to speed.

Gnus supports _many_ ways to tweak the messages, we'll expose some more of that, and where possible hook them up with the existing keybindings, to minimize friction. Some of the settings will work, other won't. Anyway, as one data-point, I've been using the gnus-based mode since mid-2018 or so, and am not missing much :)

The `e` (extract) things was a bug, I'm not using helm either. Anyway, should be fixed now.

For verification, you can use `mm-verify-option` to `'known` to auto-verify messages; this can be slow in some cases though.

**Comment by nils-schween** [comment]
@theophilusx thanks for your explanations. I am also always running the dev version and I agree it is very stable. And of course, I love to learn about the newest features. @djcb thank you - now extracting attachments with `e` works again. And opening links with `g` is working. That's great! - these are the two keybindings I am using most frequently. I set `mm-verify-option` to `'known`; it works like a charm. But since pulling the latest changes, I get the following error message: 
```
Error (use-package): mu4e/:config: Symbol’s value as variable is void:
mu4e-view-attachment-actions
```
But that's perfectly fine for me. I just removed the actions I defined for the attachments. (I thought I would be using them, but I did not anyway.
I am looking forward to the documentation of gnus article view. If I can do something to support you with this, let know.  Should I close the issue? Or do we wait for other users to report their experiences with gnus?

**Comment by nils-schween** [comment]
Oh, I just noticed something else, which is rather important to me. When I use the keybinding `R` to reply to an email, the original text of the email is copied into the compose buffer. When I am using mu4e-view-mode everything is copied correctly. But when I use gnus article mode all letters with accents on them (e.g. `ü, ä, ö` or also `ß` ) are replaced with strange strings (e.g. `=C3=BC, =C3=A4, =C3=B6`), or in some cases with numbers (e.g. `ü`= `\303\274`) and in other cases everything is copied correctly. Is there something I can do about this?

**Comment by djcb** [comment]
Can you attach an example message where this happens?

**Comment by nils-schween** [comment]
@djcb I just pulled the latest commits and it is working again.  Really, thanks a lot. In case I have to attach an email: I do not know how and in what format I have to export an email. Is there some built-in function in mu4e for this purpose? Or what do I have to do to attach a message?

**Comment by theophilusx** [comment]
nils-schween ***@***.***> writes:

> @djcb I just pulled the latest commits and it is working again. Really, thanks a lot. In case I have to attach an email: I do not know how and in what
> format I have to export an email. Is there some built-in function in mu4e for this purpose? Or what do I have to do to attach a message?
>

Have a look at the 'capture message' action. While I've never used it, I
think it might address your requirement. Basically, you mark (capture) a
message which you can then add to another message. Personally, I just
forward an email if I need to send it to someone.


--
Tim Cross

**Comment by djcb** [comment]
Or, while looking at the message:
`.` (to get to the raw view), then `C-x C-w ~/example.txt RET` to save the message, and then you can attach it.

**Comment by cantao** [comment]
> @theophilusx thanks for your explanations. I am also always running the dev version and I agree it is very stable. And of course, I love to learn about the newest features. @djcb thank you - now extracting attachments with `e` works again. And opening links with `g` is working. That's great! - these are the two keybindings I am using most frequently. I set `mm-verify-option` to `'known`; it works like a charm. But since pulling the latest changes, I get the following error message:
> 
> ```
> Error (use-package): mu4e/:config: Symbol’s value as variable is void:
> mu4e-view-attachment-actions
> ```
> 
> But that's perfectly fine for me. I just removed the actions I defined for the attachments. (I thought I would be using them, but I did not anyway.
> I am looking forward to the documentation of gnus article view. If I can do something to support you with this, let know. Should I close the issue? Or do we wait for other users to report their experiences with gnus?

Same problem here with `mu4e-view-attachment-actions`, that I really miss. Will it be re-enabled sometime in the future, or am I doing something wrong?

Thank you very much!

**Comment by djcb** [comment]
`mu4e-view-attachment-actions` should not give you errors in gnus-mode, but they don't work there. In a gui, you can try mouse right-clicking the mime-part. If that's not enough, `(setq mu4e-view-use-gnus nil)`.

**Comment by cantao** [comment]
That's weird. I have `(setq mu4e-view-use-gnus t)`, but `mu4e-view-attachment-actions` is not defined. I compiled mu from the sources and I'm using it with Doom Emacs.

**Comment by thierryvolpiatto** [comment]
Renato Fernandes Cantão ***@***.***> writes:

> That's weird. I have (setq mu4e-view-use-gnus t), but
> mu4e-view-attachment-actions is not defined.

Trying to require `mu4e-view-gnus` may help.

-- 
Thierry

**Comment by djcb** [comment]
That shouldn't be necessary with the latest (`2437dc27`).

**Comment by djcb** [comment]
I think all issues in this ticket have been resolved, closing this. Please file new tickets for other problems, thanks!
