### ISSUE TITLE
Mu/Guile revamp after 1.8

### ISSUE THREAD

**Issue by sidhu1f** [djcb/mu#1982]
Thanks for mu and the guile interface!

Earlier the guile interface used to support mu:save-as that was very convenient, for example, to save attachments in files.  However, above functionality was subsequently removed (issue #1408).

Any chance of reintroducing this functionality? Alternately any way to write attachments out to a file? Be a great help.

**Comment by djcb** [comment]
Oh, that's ancient code! The guile interface has been neglected a bit for the last few releases, have a vague plan for revamping it... but that will take a while.

For now, I'll take this is as an RFE reminder.

**Comment by sidhu1f** [comment]
If there is guile code to be written/modified, I would be happy to pitch in.  Could you please provide some idea of what needs to be done?

**Comment by djcb** [comment]
Ha! So as per the (hopefully imminent) 1.8 release, the `guile/` code is _officially_ deprecated. However, I plan on adding something new, which takes better advantage of the rest of the new infrastructure. E.g. in 1.8 we have a cached s-exp for each message in the database, which we can use directly from Guile, rather than having to go between C and Guile for each field.

Anyway, it's something for the future. I'll hijack this ticket for keeping track :-)

**Comment by djcb** [comment]
Moved this to IDEAS.org
