### ISSUE TITLE
[mu4e rfe] Wrapping of lines by default in message-mode

### ISSUE THREAD

**Issue by pbeliveau** [djcb/mu#2030]
**Is your feature request related to a problem? Please describe.**
Somewhat - mu4e is not on the list of recommended email client on [useplaintext.email](https://useplaintext.email/#recommended-clients). Meanwhile, Gnus and wanderlust are on the list.

**Describe the solution you'd like**
The solution is pretty simple but somewhat opinionated. Gnus and wanderlust use auto-fill by default when composing new messages. To be a recommanded email client, you have provide adequate default. Mu4e is missing the wrapping my default [1]

[1] [Email list reply from maintainers of the useplaintext.email pointing to auto-fill](https://lists.sr.ht/~sircmpwn/public-inbox/%3C87o8u119nz.fsf%40adocentyn.io%3E)

**Describe alternatives you've considered**
No alternative to be in the recommended list.

**Additional context**
To clarify, mu4e configuration to make it with the recommended default is provided on the website. However, it doesn't come with the adequate baked-in default to make it recommended as-is like Gnus or wanderlust.

**Comment by djcb** [comment]
Have no strong opinions about that, but please ask on the mailing-list as see what people think about changing the default -- thanks!

**Comment by pbeliveau** [comment]
Great! I forwarded the item to the list. [1]

[1] https://groups.google.com/g/mu-discuss/c/h_3YhkbE-sw

**Comment by tsdh** [comment]
I don't quite understand.  As far as I can see, mu4e does wrap/auto-fill with stock settings (because `message-mode does so which is the parent mode of `mu4e-compose-mode`).

Mu4e does not wrap/auto-fill if `mu4e-compose-format-flowed` is non-nil.  That is correct.  In that case the wrapping to `fill-flowed-encode-column` chars (default, 66) is done later when sending the message.

So what's the actual complaint useplaintext.email raises?  Should format=flowed be the default?  (At least they give instructions on how to do so with mu4e but I don't think the recommended Gnus uses that by default...)

**Comment by pbeliveau** [comment]
That's the reason to not recommend it by default:

> No, I'm talking about hard-wrapping lines. As I understand, something
> along the following lines is required:
>
> (add-hook 'message-mode-hook 'auto-fill-mode)

On the main git (rolling) version, I can see that auto-fill is enabled in m4ue:compose by default and flowed is nil. If someone else could confirm on the latest release (1.4.x), I'll create a pull request for the useplaintext.email !

**Comment by pbeliveau** [comment]
Tassilo Horn ***@***.***> writes:

> I don't quite understand. As far as I can see, mu4e does 
> wrap/auto-fill
> with stock settings (because message-mode does so which is the parent
> mode of mu4e-compose-mode`).
>
> Mu4e does not wrap/auto-fill if mu4e-compose-format-flowed is non-nil.
> That is correct. In that case the wrapping to 
> fill-flowed-encode-column
> chars (default, 66) is done later when sending the message.
>
> So what's the actual complaint useplaintext.email raises? Should
> format=flowed be the default? (At least they give instructions on how 
> to
> do so with mu4e but I don't think the recommended Gnus uses that by
> default...)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

I commented a few days ago on the issue in the repo.
https://github.com/djcb/mu/issues/2030#issuecomment-864270288

Essentially, if someone could confirm that the stable release enables
auto-fill by default in mu4e:compose mode, that would do it.

-- 
Philippe
PGP Fingerprint: 0x9E66C45D0B0AF826

**Comment by tsdh** [comment]
> I commented a few days ago on the issue in the repo.
> https://github.com/djcb/mu/issues/2030#issuecomment-864270288
>
> Essentially, if someone could confirm that the stable release enables
> auto-fill by default in mu4e:compose mode, that would do it.

I run the master version and my config only works with that.  But I did
a minimal test.

  - Install mu 1.4.15 system-wide with my package manager.
  - Create a test user.
  - Fire up emacs -Q (27.2).
  - Load mu4e.el from the 1.4.15 install.
  - Copy a draft mail from my "real" mu so that I have headers and the
    --text follows this line-- set properly.
  - Find that draft with the testuser / released mu emacs.
  - M-x mu4e-compose-mode
  - auto-fill-function is set to message-do-auto-fill and fill-column is
    70 (as are the defaults of message-mode which mu4e-compose-mode
    inherits from) and indeed when typing the lines are automatically
    wrapped around.

HTH,
Tassilo

**Comment by pbeliveau** [comment]
I've sent a patch to [useplaintext.email](https://useplaintext.email/) repository and it was accepted [1]:

![image](https://user-images.githubusercontent.com/9312223/125470808-b9932d35-05c8-4865-902a-26bbcfd19314.png)

I will close this issue now.

[1] [Link to patch.](https://lists.sr.ht/~sircmpwn/public-inbox/%3C20210710212346.181676-1-pm%40pbeliveau.me%3E#%3CCCRUK1WXMZQ1.3P6T09SNH02WF@sayaka%3E)
