### ISSUE TITLE
[mu bug] (1.6.0) mu index is not finding new messages

### ISSUE THREAD

**Issue by vnckppl** [djcb/mu#2066]
**Describe the bug**
When I run `mu index` no new messages are being found, even when I just downloaded new messages with `mbsync -a`. I am using mbsync on Mac OS to sync my Maildir. I updated from 1.4.15 where this worked. This problem already happens on the commandline, so probably unrelated to mu4e. 

This issue is likely related to: https://github.com/djcb/mu/issues/2064. The difference is that I am not able to index any new messages, regardless of wether I use the --lazy-check flag or not. 

**To Reproduce**
- update maildir with mbsync
- send yourself an email
- update maildir with mbsync
- run mu index
- the indexer does not show any new / updated messages

**Environment**
- macOS Mojave 10.14.6
- Emacs 27.2 (https://github.com/railwaycat/homebrew-emacsmacport)
- mu 1.6.0 (homebrew)
- Maildir is synced with mbsync

**Checklist**
- [x] you are running either the latest 1.4.x release, or a 1.5.11+ development release (otherwise, please upgrade).

**Comment by nbarrientos** [comment]
The same happened to me on Linux when I upgraded from 1.4.15 to 1.6. `mu index` was not finding new e-mail, even though there was unread stuff in my maildirs. I had to re`init` and re`index` all my mail to get it to work again.

**Comment by rougier** [comment]
Same issue and I too solved it by re `init` / re `index`.

**Comment by Chris00** [comment]
Same here.  For the record, the message when running `mu index` in the shell was:
```
indexing maildir ~/Maildir -> store ~/.cache/mu/xapian
\ indexing messages; processed: 220; updated/new: 220; cleaned-up: 0
** (mu:413418): CRITICAL **: 09:08:36.771: commit: xapian error 'Ran off end of freelist (43695, 396)'
/ indexing messages; processed: 242; updated/new: 242; cleaned-up: 2

** (mu:413418): CRITICAL **: 09:08:36.833: ~Private: xapian error 'Ran off end of freelist (34409, 5744)'
terminate called after throwing an instance of 'Xapian::DatabaseCorruptError'
Aborted
```

**Comment by michitux** [comment]
I have the same issue after upgrading to 1.6.0 on Arch Linux. When turning debug logging on, I found that in fact `mu` skips all messages because they are too big. `mu info` indeed reports `max-message-size  : 0` (and `batch-size        : 0` in case that matters). A quick a quick search showed that 10dbddec798842ae550eb70594665aa7c6010c23 introduced this output in `mu info` and thus indeed this seems to be new. There also seem to be new, equivalent parameters to `mu init` that are not documented in its man page. So apparently an upgrade to 1.6.0 needs a full rebuild of the database as there is no way to set these parameters with an existing database? It would be good to document that in the release notes if this is the intended behavior.

**Comment by djcb** [comment]
Yeah, seems there's some incompatibility... I've bumped the database schema version so a re-init is enforced for 1.6.1; I've tried to convey that message in the cmdline / mu4e error logging as well, and added a note to NEWS.

Thanks for the report.
