### ISSUE TITLE
[mu4e rfe] Add support for storing emails in postresql

### ISSUE THREAD

**Issue by telmich** [djcb/mu#2091]
**Is your feature request related to a problem? Please describe.**

As the xapian DB seems to be rather limited for more than 1M messages and postgresql is known to scale well, I suggest to add postgresql backend support.

**Describe the solution you'd like**

I see multiple versions to solve this:

- keep the maildir or similar as a source and use postgresql for searches
- import all messages into postgresql

I think importing all messages into postgresql might be easier to handle, but might be the most foreign to new users as well.

**Describe alternatives you've considered**

- Maybe Multi-threading for mu?

Given the experience with xapian over the last years, I have some doubt on the scaling possibilities.

**Additional context**

I could contribute the backend part, importing / indexing into postgresql. I am not so familiar with elisp and UIs, but if there were functions that could be overwritten with (postgre)SQL queries, then this should be a rather easy implementation.

**Comment by djcb** [comment]
Haven't seen evidence that Xapian is slow, moreover, it would be a massive amount of un-fun work -- 'rather easy' doesn't quite capture it! So no, this won't happen.

**Comment by Chris00** [comment]
The documentation of Xapian says that it [supports database files > 2GB](https://xapian.org/features) and can store [> 100 million mail messages](https://xapian.org/docs/scalability.html).

**Comment by theophilusx** [comment]
I would add as someone who has spent many years working with Postgres
and significant time as a DBA responsible for DB tuning etc, that moving
from Zapian to Postgres would be a non-trivial move and is unlikely to
exhibit better performance except in a few rare pathological cases. In
fact, given the way Postgres indexing works, additional network
overhead, etc, in most cases, it would likely be slower, would require
much higher maintenance and in general, be more of a hassle than a
benefit.

Postgres is a great database, but I don't think it would be suitable for
this application. I'm also not convinced that the cause of performance
issues is due to Xapian. However, I only have approx 1M messages and
have not experienced any performance issues so far.

**Comment by telmich** [comment]
@theophilusx Can you let me know how long the index process is for you? For me it can easily take 2 minutes in which mu4e is completely blocked. I think 1M to 1.5M messages should not make a big difference. I recently even tried to optimise by archiving messages into a per-year folder instead of "just one archive", which helped a litte bit with the perfomance.

Overall I like mu4e a lot, but the performance issue has over and over become very tricky to use it at all for me, that is why I was suggesting to use postgres, which I am rather sure should work without problems with some million table entries, especially if indexes are set right.

@Chris00 I am far past 2GB sizes, but way below the 100M size:

```
[16:53] nb3:xapian% ls -alh
total 11G
drwx------ 2 nico nico 4.0K Aug 16 16:45 .
drwx------ 4 nico nico 4.0K Mar 30 03:49 ..
-rw------- 1 nico nico    0 Aug 16 16:09 flintlock
-rw------- 1 nico nico  148 Aug 16 16:45 iamglass
-rw------- 1 nico nico 6.3G Aug 16 16:45 position.glass
-rw------- 1 nico nico 2.6G Aug 16 16:45 postlist.glass
-rw------- 1 nico nico 2.0G Aug 16 16:48 termlist.glass
```

@djcb Reading https://getting-started-with-xapian.readthedocs.io/en/latest/concepts/indexing/databases.html#concurrent-access it sounds as if concurrent access to the DB during indexing *is* possible, my last state was that either it was not possible at all or not implemented in mu4e - is the situation different now?

**Comment by theophilusx** [comment]
I don't see the blocking behaviour you report at all. Even if I use U to
force an update and index of new messages, I can still view messages
while that activity is underway. I have mu4e set to retrieve mail every
10 minutes and I never even notice it. New messages will just 'appear'
in the header. I don't even worry about how long it takes to index as I
don't see it and don't care about it. For example, I was replying to
another message when this one arrived. As soon as I completed the reply
and sent it, your message just appeared in the header and I opened it to
reply. The only 'blocking' I see is when sending the message - I tried
the async version of smtpmail, but found it error prone and the blocking
when sending is rarely more than a few seconds. 

The only 'minor' issue I see is that if I'm replying to a message and
the automatic background fetch+index runs, I will likely have a partial
copy of the message I was replying to appear in the draft folder of my
mail provider. Not a big issue and I just delete it when this happens. 

In my case, the indexing is nothing compared to how long it takes for
mbsync to retrieve the messages from my mail providers. I occasionally
get an error due to some sync issue with mbsync, but that is easily
resolved by deletting the offending message from the maildir and
re-syncing (often, if it isn't a large archive folder, I'll just delete
the directory and re-sync as that is easier/faster)). 

I do know you can run into issues if you have the update interval set
too small because a new update can fire off while the current one is
still running. 

My mu4e settings (with exception of contexts and bookmarks, are

(setq mu4e-attachment-dir (expand-file-name "~/Desktop")
      mu4e-get-mail-command "mbsync -a"
      mu4e-hide-index-messages t
      mu4e-headers-include-related nil
      mu4e-change-filenames-when-moving t
      mu4e-context-policy 'pick-first
      mu4e-compose-context-policy nil
      mu4e-use-fancy-chars t
      mu4e-view-fields '(:from :to :cc :subject :date :attachments)
      mu4e-view-scroll-to-next nil
      mu4e-view-show-addresses t
      mu4e-view-use-gnus t
      mu4e-update-interval (* 60 10))

I'm running Emacs 28 on a Ubuntu 21.04 system. I use spacemacs, but I'm
not really using their mu4e configuration. I do load the mu4e layer, but
have my own configuration which overrides most of their settings. Both
mu and mu4e are built from the master HEAD.

**Comment by theophilusx** [comment]
Nico Schottelius ***@***.***> writes:

> Overall I like mu4e a lot, but the performance issue has over and over become very tricky to use it at all for me, that is why I
> was suggesting to use postgres, which I am rather sure should work without problems with some million table entries, especially
> if indexes are set right.

the big issue with Postgres is the way it manages indexes. Unlike other
systems, when you modify a table row, Postgres actually generates a new
row. Unfortunately, this means any indexes need to be rewritten because
the row address has changed. It also means you have to vacuum the table
regularly and every 6 - 12 months, you should do a full vacuum (because
fast vacuum cannot re-lcaim all the freed space), which is a very slow
operation, during which time the db is unavailable.

Other databases, like Oracle and even MySQL/Maria do not suffer from
this issue. Despite this, MySQL has other issues and while the Oracle
RDBMS is an excellent product, all the rest of their stuff is horrible
and installation/maintenance is non-trivial. I still prefer Postgres and
there are many things you can do to help ensure performance, but that
involves skills most people don't have and it cannot be automated.

The indexing and maintaining performance with row updates is the main
reason Uber switched from Postgres to MySQL.

It would be nearly impossible to get high performance out of Postgres
across all versions and all use cases. It would only be worthwhile for
users with extremely high numbers of messages and even then, ensuring
good performance would be difficult to get consistently. It woldn't be
just a simple move from Zapian to postgres either - a whole additional
layer of db connection management would be necessary as well as a mu ->
pg layer. A lot of work for only a small number of users.
