### ISSUE TITLE
Error (mu4e): expected schema-version 452, but got 451; please use 'mu init'

### ISSUE THREAD

**Issue by tmfe61** [djcb/mu#2103]
mu init shows schema 452. 
I don't know where this schema 451 is coming from.

OS: Linux Mint
mu-version: 1.6.3
mu4e: 1.6

**Comment by djcb** [comment]
Try `mu info`, re-`init` if  necessary, as the error suggests. Restart emacs etc. If you still get the error, your mu finds some _different_ store; so check the mu paths in your mu4e setup. Good luck!

**Comment by muradm** [comment]
@djcb, faced same issue today, in my case i had the following issue: first i run `mu init` months ago, and supplied 5-6 `--my-address` fields which for my old mail addresses i used for life time, now even `mu info` is failing, so i'm not able to see what those addresses were, and i have to go over emails i sent for years again in order to acquire values for `--my-address` fields.

My question is, is it possible to acquire initial `--my-address` fields when `mu info` fails with `error: expected schema-version 452, but got 451; please use 'mu init'`?

I tried to look into files under `~/.cache/mu` to find them, but could not see any sign of them. If there is no way to see how `mu init ...` was initially run, may be you could store initial `my init ....` command under `~/.cache/mu/.initialized-with` or alike?

**Comment by djcb** [comment]
Try something like:
```
 $ xapian-metadata get ~/.cache/mu/xapian personal-addresses
```

**Comment by muradm** [comment]
@djcb, thanks that helped to reconstruct `mu init` command

**Comment by timmli** [comment]
In my case, upgrading from v1.4.x , `mu4e-mu-home` was pointing to the wrong directory (`~/.mu/`). The following worked for me:

    (setq mu4e-mu-home "~/.cache/mu")
