### ISSUE TITLE
[mu4e bug] Wrong buffer display after sending an email

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#2132]
**Describe the bug**
When composing an email (say replying to a message) when the `*mu4e-headers*` and `*Article*` buffers are displayed in the same frame, the `*draft*` buffer replaces the `*Article*` one (so far, so good).  When the email is sent, the `*mu4e-headers*` buffer takes the place of the `*draft*` one — thus 2 `*mu4e-headers*` buffers are displayed in a split view.  I'm expecting the `*Article*` buffer to replace back the `*draft*` one.

**To Reproduce**

Just send an email.

**Environment**
Emacs 27.1
Mu devel (commit #191f0f47)

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by theophilusx** [comment]
Confirm I see same behaviour with latest dev HEAD.

**Comment by djcb** [comment]
I think this has been with us for a long time.

The related code hasn't changed in ages (`mu4e-message-kill-buffer`), perhaps something changed with the gnus-view?

**Comment by thierryvolpiatto** [comment]
I confirm the bug as well.  The reason is that `mu4e-get-view-buffer` returns a buffer-name instead of returning a buffer object, so `buffer-live-p` in `mu4e~switch-back-to-mu4e-buffer` fails.
Also using `gnus-article-buffer` is not the best thing to do if gnus is used along mu4e e.g. for news, in this case it would be better to use a `defconst` like `mu4e-headers-buffer-name` and use `get-buffer` just like `mu4e-get-headers-buffer` does.
Also both docstrings are wrong and misleading (hence this bug) because they say "get the name of the buffer" whereas they should be "get buffer...".

```diff
diff --git a/mu4e/mu4e-helpers.el b/mu4e/mu4e-helpers.el
index 7b533f89..7cf029a5 100644
--- a/mu4e/mu4e-helpers.el
+++ b/mu4e/mu4e-helpers.el
@@ -111,15 +111,16 @@ buffer list.")
   "Name of the buffer for message headers.")
 (defconst mu4e-embedded-buffer-name " *mu4e-embedded*"
   "Name for the embedded message view buffer.")
+(defconst mu4e-view-buffer-name "*Article*"
+  "Name of the view buffer.")
 
-(defun mu4e-get-headers-buffer()
-  "Get the name of the headers buffer."
+(defun mu4e-get-headers-buffer ()
+  "Get the buffer object from `mu4e-headers-buffer-name'."
   (get-buffer mu4e-headers-buffer-name))
 
-(defun mu4e-get-view-buffer()
-  "Get the name of the view buffer."
-  ;; avoid a 'require.
-  (when (boundp 'gnus-article-buffer) gnus-article-buffer))
+(defun mu4e-get-view-buffer ()
+  "Get the buffer object from `mu4e-view-buffer-name'."
+  (get-buffer mu4e-view-buffer-name))
 
 (defun mu4e-select-other-view ()
   "Switch between headers view and message view."

```

**Comment by thierryvolpiatto** [comment]
I see also several calls of `mu4e-get-view-buffer` that fails in the same way with `buffer-live-p`, other calls are working because callers accept `BUFFER-OR-NAME` as arg (like `get-buffer-window`).

**Comment by haji-ali** [comment]
I can also confirm this issue. In general, I have been trying to customize how the various mu4e windows are positioned with `display-buffer-alist` but it has been very difficult because the code for window creation/replacing is peppered throughout `mu4e`. I think having a more centralized window management module would make things much easier.

**Comment by djcb** [comment]
Closing this, as it has been fixed.
