### ISSUE TITLE
[mu4e bug] ^M showing up in emails

### ISSUE THREAD

**Issue by antoine-levitt** [djcb/mu#2133]
In some emails, I get explicit ^M characters in the line endings of the email (not of the headers), with mu4e-view-use-old t. I started noticing this recently, possibly when updating to 1.6.x. Tested in the latest 1.6.6. I can send privately examples of emails that trigger this and emails that don't if that helps.

CC @Chris00 because https://github.com/djcb/mu/issues/1975 looks related, but I couldn't figure the relationship.

**Comment by Chris00** [comment]
Some reactions as I read.
- Get rid of `mu4e-view-use-old` set to `t`.  It will disappear in the next version of mu anyway.
- You should describe how you fetch emails because the culprit may be in these tools.
- Why didn't you respect the template for bug reports?

**Comment by antoine-levitt** [comment]
> Get rid of mu4e-view-use-old set to t. It will disappear in the next version of mu anyway.

Both this and making a proper bug report that includes full reproducibility requires time that I don't have right now. To be honest, I have multiple issues with mu4e and it feels like updating mu to close one issue opens two new ones for me, and tracking them down takes more time than I have to devote to it. I thought it was better to make a bug report since this occured quite recently and it looked like that it was related to that other issue . Feel free to close if you prefer to have only perfect bug reports.

> You should describe how you fetch emails because the culprit may be in these tools.

I doubt it, I use mbsync, have been for a few years and I didn't update it recently.

**Comment by Chris00** [comment]
I understand how you feel about your time being precious.  You will then be also sensitive I guess to fact that us, developers, use our free time to develop, fix, respond to issues,...  In the end, it is @djcb who has the final word on closing or not this issue.

In order to make possible for us to try to reproduce the bug, a copy of the file of the mail that triggers the problem must be attached to this report.  You will have to append `.txt` to the filename so Github accepts it.

**Comment by antoine-levitt** [comment]
> You will then be also sensitive I guess to fact that us, developers, use our free time to develop, fix, respond to issues,...

Obviously, this is open source. I wish you guys would be more conservative about not breaking things, but that does come at the price of slower development of new features and you're the only ones who decide what you want to work on. If my issue is unwelcome again feel free to close it.

Attached is an email (a github issue email) obtained from mu4e-view-raw-message that shows the problem, with some headers changed/removed.
[mail.txt](https://github.com/djcb/mu/files/7149730/mail.txt)

**Comment by thierryvolpiatto** [comment]
Christophe Troestler ***@***.***> writes:

> I understand how you feel about your time being precious. You will
> then be also sensitive I guess to fact that us, developers, use our
> free time to develop, fix, respond to issues,...

+1.

> In order to make possible for us to try to reproduce the bug,

Don't think it is a bug in mu4e, one can use `article-remove-cr` in such cases.

-- 
Thierry

**Comment by Chris00** [comment]
This is how the message you sent displays for me (with the devel version of mu):
![image](https://user-images.githubusercontent.com/1255665/132996709-ccffafc8-6c12-4415-bca4-88ef87b3342e.png)

The message file does not contain `^M`.  Maybe you want to send one in a tarball by email (see profile)?

**Comment by antoine-levitt** [comment]
> Don't think it is a bug in mu4e, one can use `article-remove-cr` in such cases.

That indeed removes the ^M. I didn't change anything recently other than the mu version, so I'm still guessing it has to do with recent changes there.

> This is how the message you sent displays for me (with the devel version of mu):

Looks to be the gnus-based viewer? The gnus viewer doesn't have this issue for me, only the "old" one.

**Comment by Chris00** [comment]
> Looks to be the gnus-based viewer? The gnus viewer doesn't have this issue for me, only the "old" one.

It is.  In the devel version, there is no old viewer anymore.

**Comment by theophilusx** [comment]
Antoine Levitt ***@***.***> writes:

>  Get rid of mu4e-view-use-old set to t. It will disappear in the next version of mu anyway.
>
> Both this and making a proper bug report that includes full reproducibility requires time that I don't have right now. To be
> honest, I have multiple issues with mu4e and it feels like updating mu to close one issue opens two new ones for me, and
> tracking them down takes more time than I have to devote to it. I thought it was better to make a bug report since this occured
> quite recently and it looked like that it was related to that other issue . Feel free to close if you prefer to have only perfect bug
> reports.

I don't help with mu4e maintenance, but I do maintain a number of open
source projects. I have a golden rule when it comes to bug reports - the
effort I put in to resolve a bug report is directly proportional to the
effort the reporter put in when submitting it.

Good bug reports are extremely useful. This is especially the case with
environments like emacs, where the setup and configuration can be
extremely varied. A good bug report will allow the maintainer (or other
interested party) to reproduce the environment and bug. Once you can
reproduce the bug, you are usually 80% there towards resolving it. 

A bad bug report is worthless. It leaves the maintainer in a position
where they have to guess as to what is going on. The issue won't be
obvious in their environment - if it was, they would have fixed it. 

This is not meant to be rude, but unfortunately, your bug report was
very poor. In addition to not following the bug report template, you
failed to mention

- Version of Emacs
- Platform (Linux, Windows, macOS, BSD, etc)
- Your mu4e configuration 
- Whether you have tried running Emacs -Q and just loading mu4e and was
  able to reproduce the issue

Providing this information in your original bug report would also reduce
your time spent on this as it wouldn't then be necessary to ask all
these additional questions.

Note that if your too pressed for time to submit a complete bug report,
but want to discuss/mention issues, concerns, suggestions etc, there is
a google group for mu4e. Posting there and getting some general feedback
might help and could provide some guidance on how to submit a bug report
which is actionable.

The first thing I would try is to run Emacs -Q and then just load a
minimal configuration for mu4e and see if you can reproduce the problem.
If you cannot, then the issue is to do with your configuration (it could
easily be something which seems completely unrelated to mu4e). If you
can reproduce it, then update this bug report with the configuration you are using
as this will help others to reproduce the issue, which will help get a
resolution faster.

**Comment by antoine-levitt** [comment]
> I have a golden rule when it comes to bug reports - the
effort I put in to resolve a bug report is directly proportional to the
effort the reporter put in when submitting it.

Yeah, I have the same policy in reverse: the effort I spend making a good bug report is proportional to the likelihood it'll get acted upon. My last experiences following mu issues were a popular PR that went unmerged despited repeated bumps, only to be declared obsolete by the change to the new viewer, and a bug I reported with as much information as I could (spending significant time trying to figure out what was going wrong) without progress. That doesn't really inspire me to write the perfect bug report. Again that's fine: you don't owe me anything, I don't owe you anything, everything's as it should be given the situation.

In any case this issue is specific to the old viewer, which is not supported anymore, so there isn't really any point discussing it further.
