### ISSUE TITLE
Mu4e not Syncing from one Account

### ISSUE THREAD

**Issue by Raghav-Dixit** [djcb/mu#2134]
**Describe the bug**
I wanted to add my disroot.org address to mu4e, but it does not seem to sync. It did sync for other accounts I had. I have the same exact code in my `.mbsyncrc` for all accounts, just replaced the names of the variables and accounts. I extracted all of the passwords using `pass acc_name`. I do not think it is a problem with the disroot IMAP because it seems to be working with other email clients.

**Environment**
OS: macOS v11.5.2
Emacs v27.2
Doom Emacs v3.0.0 (tried with and without, mu4e does not sync)
mu4e v1.6.5

**Checklist**
- [x] you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those
- [x] you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those)
- [x] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**My Config**
```

# ACCOUNT INFORMATION
IMAPAccount raghav-disroot
# Address to connect to
Host disroot.org
User something@disroot.org
PassCmd "pass acc"
AuthMechs LOGIN
SSLType IMAPS
SSLVersions TLSv1.2
# CertificateFile /etc/ssl/certs/ca-certificates.crt


IMAPStore raghav-disroot-remote
Account raghav-disroot


MaildirStore raghav-disroot-local
Path ~/Maildir/raghav-disroot/
Inbox ~/Maildir/raghav-disroot/INBOX


Channel raghav-disroot
Far :raghav-disroot-remote:
Near :raghav-disroot-local:
Patterns *
Create Both
Expunge Both
SyncState *
```

**Comment by Raghav-Dixit** [comment]
I forgot to mention, it does not show any errors. Just doesn't sync.

**Comment by djcb** [comment]
Hmmm, you'll have to be very specific on what you think mu is (not) doing correctly, check the logs etc., and confirm the message files are being downloaded etc.. Right now this is not actionable.

**Comment by theophilusx** [comment]
This sounds like an mbsync issue rather than an mu4e or mu issue.


You probably need to find an mbsync forun to ask about this. Mu4e relies
on 3rd party programs like mbsync to handle synchronisation between
local and remote servers. The fact it is working with other mail servers
means that either your .mbsync settings are incorrect or there is
something about the remote mail service which is incompatible with
mbsync. My guess is that it is your local configuration which is
incorrect. 

Things I would try are

- Check the mbsync manual and add some of the recommended switches to
  turn on debugging/logging etc. 

- Comment out the other mail accounts so that only this account is
  'active'. This will make running mbsync faster and avoid cluttering
  output with information fro the other mail accounts.

- Replace the passCmd with an actual 'pass <password>' line (just to get
  things working - restore passCmd later once you have things working)

- Run just 'mbsync -a' in a terminal to see what the output is

don't worry about mu4e until you know mbsync is working.

**Comment by Raghav-Dixit** [comment]
`mbysnc -a` does not return any errors. I'll try to change the PassCmd to my actual password instead of retrieving it through pass.

**Comment by Raghav-Dixit** [comment]
Update: It's working! Here is what I did:
1. Commented my other accounts
3. ran `mbsync -a`
4. `rm -rf ~/.cache/mu/xapian`
5. `mu init --maildir=~/Maildir`
6. `mu index`
7. Uncommented my other accounts.
8. Repeated Steps 1-6, and messages seem to be getting through.
I don't know where things went wrong earlier.
