### ISSUE TITLE
[mu bug] Unable to search for subjects containing asterisks (*)

### ISSUE THREAD

**Issue by polaris64** [djcb/mu#2278]
**Describe the bug**
I have been using queries such as `subject:/^\*\*\*\*\*SPAM/` to match messages marked as spam. However after updating to mu 1.8.1 these queries no longer work.  Up until today I was running mu 1.6.11 and queries like this worked fine.

This happens in both `mu` and `mu4e`.

I need to match the asterisks as well as the word "SPAM" as this uniquely identifies spam messages marked as such from my spam filter rather than e.g. legitimate messages which happen to mention "spam" in the subject.

**To Reproduce**
Run:  `mu find 'subject:/SPAM/'`, output: -

```
Wed 15 Jun 2022 10:27:47 CEST [...] <[...]> *****SPAM***** [...]
Wed 15 Jun 2022 15:56:23 CEST [...] <[...]> *****SPAM***** [...]
```
Run any of: -
`mu find 'subject:/^\*\*\*\*\*SPAM/'`
`mu find 'subject:/\*\*\*\*\*SPAM/'`
`mu find 'subject:/*****SPAM/'`
`mu find 'subject:*****SPAM'`

Output for each is: -

```
no matches for search expression
```

**Environment**
Arch Linux, mu 1.8.1, Emacs 28.1.50

**Checklist**
- [X] you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).

**Comment by djcb** [comment]
That it worked earlier is a bit of an accident..., in general searching for special characters doesn't work too well with Xapian. Anyway; the below patch should restore the older behavior (you need to re-index).  However, it makes the xapian database a lot bigger, so I'm a bit reluctant to merge it.

```
modified   lib/message/mu-document.cc
@@ -47,6 +47,9 @@ add_search_term(Xapian::Document& doc, const Field& field, const std::string& va
 		Xapian::TermGenerator termgen;
 		termgen.set_document(doc);
 		termgen.index_text(utf8_flatten(val),1,field.xapian_term());
+		 /* also add as 'normal' term, so some queries where indexer
+		  * eats special chars also match */
+		doc.add_term(field.xapian_term(val));
```

**Comment by polaris64** [comment]
Thanks for the explanation and for providing a patch to restore the previous behaviour. I might have to rethink how I'm handling spam in that case.

Would it be possible to add this functionality as an option when running `mu index` perhaps?

**Comment by theophilusx** [comment]
Just out of interest, what characters are considered 'special'
characters?

For the OP, the solution I use is to sort the messages into a spam
folder on the server and then pull that folder down using mbsync. I find
this has two main advantages

  - Faster. Less work being done locally.
  - Less download. I actually don't include the spam folder in my
    'normal' mbsync runs which occur every 10 minutes. Instead, I grab
    that folder separately 3 times per day (I can also manually grab it
    at any time).

Where I was working, possible spam messages had '[SPAM?]' added as a
prefix to the subject header (as well as an 'X-spam-score:' header) and I
was able to use filtering on these two headers to sort messages into the
spam folder on the server. I actually use the X-spam-score header as
there is less ambiguity and it is easier to match on. It also allowed me
to control what I consider to be spam rather than using some value
chosen as a 'reasonable' cut-off for me (i.e. the 'score' at which
****SPAM is added to the subject line).  

Note that most spam tagging solutions will add one or more headers
relating to spam. It is these headers you typically want to use for
searching/sorting. The ****SPAM tagging is really for humans, not
machines and is a slow search/match approach. Check your message headers
and you may find there is a header you can use which is easier to search
for and does not include xapian 'special' characters.

**Comment by theophilusx** [comment]
Simon Pugnet ***@***.***> writes:

>  Check your message headers and you may find there is a header you can use which is easier to search for and does not include xapian
>  'special' characters.
>
> I've love to be able to filter based on X-Spam-Flag: Yes however I don't think Xapian indexes all headers. Is there a way I can include this
> header when indexing so that I can use it when querying?
>

Of course! Your quite right, those headers are not included in the
db. Probably why I do it at the server as well.

If your running your own mail server, then procmail on the server would
be the way I'd go. This will not affect anyone else on the server as you
hook procmail into the delivery process via the .,forward file in your
server account. Essentially, it just pipes each message delivered to you
through procmail, where procmail applies its rules and then puts it into
your mail server spool file(s). Provided you have not setup your mail
server to ignore .forward, you probably won't even need to update your
mail server configuration. (note that there are multiple ways to setup
procmail. It is possible to have it setup more tightly integrated into
the mail server, but it doesn't have to be). 

Procmail is an extremely powerful tool. I used it for years when I
could be bothered running my own mail server. These days, I just prefer
to outsource that to someone else!

**Comment by djcb** [comment]
`mu` only indexes some headers (see `mu fields` to get an idea). 

And yeah, I'm using `procmail` as well. Some of the external mail I get through `fetchmail`, which feeds the incoming mail through `procmail`, i.e., in `.fetchmailrc` there's something like:

```
poll imap.gmail.com with proto IMAP
      user 'example@gmail.com' there with password 'test123' is 'user' here
      options fetchall flush nokeep ssl sslproto tls1.2 mda "/usr/bin/procmail -m /home/user/.procmailrc"
```

**Comment by djcb** [comment]
Oh, an 1.8.2 restores the "asterisk search", and added a unit test for it.
```
 mu find subject:'\*\*\*\*\*SPAM\*\*\*\*\*'
```
works now.
