### ISSUE TITLE
New build system does not run install-info

### ISSUE THREAD

**Issue by whxvd** [djcb/mu#2285]
I just built and installed mu 1.8 from the ```release/1.8``` branch.

I install to `/usr/local`. With the new build system, only ```/usr/local/share/info/mu4e.info``` gets installed. But the installation probably also should involve a call to install-info, in order to create/update ```/usr/local/share/info/dir```. As far as I remember, the previous build system did that.

I have no knowledge/experience with Meson. It probably would take a lot of time for me to create a PR for this by myself.

**Comment by eli-schwartz** [comment]
You'll need

```meson
meson.add_install_script(
    find_program('install-info', required: false, disabler: true),
    get_option('prefix') / get_option('infodir'),
    skip_if_destdir: true,
)
```

**Comment by djcb** [comment]
Yeah, sadly it cannot really work without a script, esp. since it should also handle e.g `MESON_INSTALL_DESTDIR_PREFIX` (for `dist` and `install`). And indeed relying on meson 0.52 doesn't make things easier...

Anyway, I pushed an implementation that seems to work; it's in 1.8.3.

**Comment by eli-schwartz** [comment]
Sorry, but that is wrong and will break. Like I said:

> you probably want to write a custom script that checks if $DESTDIR is set and simply exits early.

You *must not* handle DESTDIR_PREFIX. If DESTDIR is set at *any* time, then install-info must not be run, because it's dangerous to create the `<prefix>/share/info/dir` index; it will contain only the information from this project, and it will include it in e.g. distribution packages, but those will then fail to install due to file conflicts with the system generated index (which is not part of any package, because it contains information merged from dozens of packages).

It will however correctly work if DESTDIR is not set, because in that case DESTDIR_PREFIX is the same as PREFIX, and when installing directly to PREFIX you can update the shared index.

**Comment by djcb** [comment]
@eli-schwartz : if I build with `--prefix=<my prefix>` I'd expect the "dir" file to be updated in the corresponding dir.

But the concern is about distros using `--prefix` to build in some directory, and then turning that into a package as-is?

**Comment by eli-schwartz** [comment]
When --prefix is used to configure the build, `install-info` should / will be run as normal. That's not the issue.

When `$DESTDIR` is used during *install*, then `install-info` should not be run, because it means that you're not doing a "real" installation, only creating a package. Nothing is installed to the --prefix anyway, just to some tempdir used by the distro packaging system.
