### ISSUE TITLE
[mu4e bug] The header title is not complete when the title contains both CJK and English characters

### ISSUE THREAD

**Issue by zzjjzzgggg** [djcb/mu#2319]
**Describe the bug**

When the email title contains both Chinese and English characters, the header title will not be shown completely.

**How to Reproduce**

Compose three emails  with subject titles as follows respectively. (Each line is one title.)
`日日日日日日日日日日日日日日日日日日日日`
`a日日日日日日日日日日日日日日日日日日日日`
`日日日日日日日日日日a日日日日日日日日日日`

That is, the first email has a title with 20 Chinese characters `日`, the second email has a title starting with a character `a`, and the third email has a title with a character `a` in the middle.

Then send these three emails to some one.

Go to the sent mails, and in `mu4e-headers`, you will observe that:
the first sent mail has a complete title,
the second sent mail has an incomplete title `a日日日日日日日日日日日日`, i.e., character `a` following 12 Chinese characters `日`, 
and the last sent mail has an incomplete title `日日日日日日日日日日a日日`, i.e., only two Chinese characters after `a`.

The subject titles of raw mails have the following codings, respectively.

The 1st one:
```
Subject: =?utf-8?B?5pel5pel5pel5pel5pel5pel5pel5pel5pel5pel5pel5pel5pel?=
 =?utf-8?B?5pel5pel5pel5pel5pel5pel5pel?=
```
The 2nd one:
```
Subject: =?utf-8?B?YeaXpeaXpeaXpeaXpeaXpeaXpeaXpeaXpeaXpeaXpeaXpeaXpQ==?=
 =?utf-8?B?5pel5pel5pel5pel5pel5pel5pel5pel?=
```
The 3rd one:
```
Subject: =?utf-8?B?5pel5pel5pel5pel5pel5pel5pel5pel5pel5pelYeaXpeaXpQ==?=
 =?utf-8?B?5pel5pel5pel5pel5pel5pel5pel5pel?=

```
**Environment**
Arch Linux, Emacs 28.1, mu/mu4e 1.8.8 (latest)

**Comment by djcb** [comment]
Cannot reproduce...  how's your `mu4e-headers-fields` defined?

**Comment by zzjjzzgggg** [comment]
```
(setq mu4e-headers-fields
      '((:date    . 12) 
        (:flags   . 6)
        (:from    . 16)
        (:subject . nil))) 
```
`XAPIAN_CJK_NGRAM` is already set. And running `mu find s:日日` also returns incomplete email titles. The version of xapian is 1.4.19.

weird.

**Comment by djcb** [comment]
Ah, when you see it in `mu find`, it's not some character rendering issue. Support for CJK in `mu` has a bunch of known problems, unfortunately, see #1428.  So I suspect what you're seeing is exactly that.

**Comment by jacknashg** [comment]
aha, found the solution, but quite weird.

A: 
(left part of attached screenshot)
clone gmime (version 3.2.13) from [gmime github](https://github.com/jstedfast/gmime), compile and use (through modify LD_LIBRARY_PATH), then "mu view" display the full subject.

B:
(right part of attached screenshot)
download gmime (version 3.2.13) from [gmime github release](https://github.com/jstedfast/gmime/releases/tag/3.2.13), compile and use, the "mu view" display only part of the subject.

i guess the sysytem installed gmime works the same way as B.

attached is screenshot showing the difference.

so, i guess the solution to the problem is to clone gmime from github, compile and install it system wide, overwriding the gmime installed from distribution (as in Arch: pacman -Ss gmime3).


![answer](https://user-images.githubusercontent.com/14989990/206717636-69089edd-b200-411f-9be1-af2880d19e07.png)
