### ISSUE TITLE
[mu bug] Mu misses Evolution mail nested maildir format

### ISSUE THREAD

**Issue by JoeOsborn** [djcb/mu#2331]
**Describe the bug**
Evolution mail seems to store emails (at least from Exchange servers) in a directory structure like `folders/maildir-name/cur/##/XXXX`, where `##` is a two-digit hex code and `XXXX` is some long hex string.  `mu index` does not recurse into the `##` folders, so it doesn't see the `XXXX` email messages (this can be fixed by changing `mu-scanner.cc:96` to `process_dir(fullpath, new_cur || is_maildir)`).  

However, `Mu::maildir_from_path` looks for the last four characters of a mail's parent directory to be '/cur' or '/new', and this check fails for such a folder layout.  I rewrote that function to:

```c++
Result<std::string>
Mu::maildir_from_path(const std::string& path, const std::string& root)
{
	const auto pos = path.find(root);
	if (pos != 0 || path[root.length()] != '/')
		return Err(Error{Error::Code::InvalidArgument,
				"root '%s' is not a root for path '%s'",
				root.c_str(), path.c_str()});

	auto mdir{path.substr(root.length())};

	auto cur_fold{mdir.rfind("/cur")};
	auto new_fold{mdir.rfind("/new")};
	bool cur_bad = cur_fold == std::string::npos;
	bool new_bad = new_fold == std::string::npos;
	if (cur_bad && new_bad)
		return Err(Error{Error::Code::InvalidArgument,
		  "cannot find '/new' or '/cur' - invalid path: %s",
		  path.c_str()});
	if (!cur_bad) {
		mdir.erase(cur_fold);
	} else { // if(!new_bad)
		mdir.erase(new_fold);
	}
	return Ok(std::move(mdir));
}
```

It seems to almost work now (messages get moved up too far when their flags change, rather than staying in the `##` subfolder), but I don't feel comfortable filing a pull request for this since mu is a large project and I don't know its infrastructure, test suite, or anything else. I'm also not very familiar with C++.

This is debatably an Evolution bug, but I am scared to touch its codebase which is much more loosely coupled and scattered among many packages.

**To Reproduce**
Synchronize GNOME Evolution mail to a server (Office 365/exchange EWS definitely has this behavior, maybe other sources do too) and try to set its folder cache as mu's mail root.

**Environment**
Latest `mu` master e7e6f2e776a36878b4ce63498b5e148350915b3f. Emacs 29.0.50. Ubuntu 22.04.1 LTS.

**Comment by djcb** [comment]
Yeah, `mu` only considers messages in `cur/` or `new/`, and not their sub-directories. Apparently Evolution uses something that is _alsmost_ like a Maildir, with those extra subdirectories. I wouldn't consider that a bug unless they claim to be Maildir-compatible. Is Evolution's format documented somewhere (outside the source code)

You could extend `mu` (as you've done) to also descend in those directories, but I don't think it's a good idea to do in `mu` itself, since now `mu` would be changing the structure that Evolution has designed for itself, possibly in incompatible ways. Esp. if it's undocumented.

I think Evolution support "normal" Maildir as well, perhaps that can be used?

**Comment by JoeOsborn** [comment]
I think you’re right, and in fact the problem may be down to evolution-ews since different plugins seem to use different message stores.  I’ll follow up with that community, but I guess this issue should be closed.
