### ISSUE TITLE
[mu4e rfe] allow to reply to a message without citations

### ISSUE THREAD

**Issue by yashasolutions** [djcb/mu#2345]
**Is your feature request related to a problem? Please describe.**
When replying to comments (github/gitlab/asana...) the whole message replied appear in the comments since it was quoted. I have searched but cannot figure out a way to disable citation of original message on reply. 

**Describe the solution you'd like**
Ideally, an alternative command to 'R' that would allow to reply without the quoted message.

**Describe alternatives you've considered**
A variable to tweak in the config would do also.

**Comment by theophilusx** [comment]
Yasha ***@***.***> writes:

> Is your feature request related to a problem? Please describe.
> When replying to comments (github/gitlab/asana...) the whole message replied appear in the comments since it was
> quoted. I have searched but cannot figure out a way to disable citation of original message on reply.
>
> Describe the solution you'd like
> Ideally, an alternative command to 'R' that would allow to reply without the quoted message.
>
> Describe alternatives you've considered
> A variable to tweak in the config would do also.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

Here is what I use

(defun tx-delete-citation ()
  (delete-region (point) (point-max)))

(defun tx-mu4e-reply (prefix)
  (interactive "P")
  (setq mu4e-compose-cite-function (if prefix
                                       #'tx-delete-citation
                                     #'message-cite-original-without-signature))
  (mu4e-compose-reply))

(define-key mu4e-view-mode-map "R" #'tx-mu4e-reply)
(define-key mu4e-headers-mode-map "R" #'tx-mu4e-reply)

With the above, if I reply by hitting 'R', all acts as normal. However,
if I do C-u R, the cited message is removed and I have an empty buffer.

In my case, due to a recent reconfiguration, my key binding is not
working. I suspect it is being over written by the mu4e compatibility
layer from evil-collections (I use evil mode).

**Comment by djcb** [comment]
The new message composer should help for this; for the no-citation part, you can e.g. let-bind message-cite-function to mu4e-message-cite-nothing. If this is a common need you could create a function my-mu4e-compose-reply-without-citation that does that.

Note: mu4e 1.11.23 has a new composer that is much closer to gnus' one, so various message- settings have better odds to work in mu4e as well. See NEWS.org for details.
