### ISSUE TITLE
[mu bug] tilde-expansion in `mu init` does not work any more.

### ISSUE THREAD

**Issue by lockywolf** [djcb/mu#2528]
**Describe the bug**
The command `mu init --maildir=~/Mail-mbsync/ --my-address='/.*@mydomain\.net/' --my-address='.*@localhost'` used to work with mu-1.8.14, but does not work with mu-1.10.5

**How to Reproduce**
I updated mu, and ran this command. Expanding the tilde manually mitigates the issue, but makes the database non-portable between users.

**Environment**
Linux, default shell is bash.

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you have read all of the above

I think this is actually the same issue as https://github.com/djcb/mu/issues/2448

No sure this can be called a bug or a feature, but what used to work in the past does not seem to work now. But even if it is closed as intended behaviour, at least it will be documented here.

**Comment by djcb** [comment]
Hmm... it's a peculiarity of at least `bash` that when you do `<command> ~/foo --option=~/bar`, it expands `~/foo` but not `~/bar`. E.g., `zsh` will expand both.

But you are right that `mu` would try to then handle the  `--option=~/bar` case. It could be argued that it's not really `mu`'s job... but since that's what it did in the past and many examples depend on it, it's probably good to restore that behavior. I'll add a change for that.
