### ISSUE TITLE
[mu4e rfe] Display Email Content in notification

### ISSUE THREAD

**Issue by eval-exec** [djcb/mu#2604]
**Is your feature request related to a problem? Please describe.**
I have set `(setq mu4e-notification-support t)` for notification support.
When a new email comes, the notification only show a subject, but did not show the email body.
It would be more benificial if mu4e can display email body in notification popup.

**Describe the solution you'd like**
Display email body in notification

**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by djcb** [comment]
mu4e's built-in notification support only shows the number of new messages; no subjects (or message contents). Perhaps you're using some other package?

Anyway, `mu4e` only knows about the difference in count of messages that match some query, and if that count > 0 concludes there are new messages, and triggers the notification. We're not currently planning to change that, but if you want, you can customize `mu4e-notification-function` to use your own function to instead of the default `mu4e--default-notification-function`, perhaps using the `mu` command-line tool to gather what you want to display. Good luck!

**Comment by OlMon** [comment]
Greetings,

Just a question to this topic:
> perhaps using the mu command-line tool to gather what you want to display

I did that, by just getting the "difference in count" newest messages. But now with the new optimization in writing the DB to the filesystem mu does not see the newest messages. What would be now a proper way to implement that? 
Is there an API for mu4e where I can get s-expressions of a query similar to `mu find`?

Cheers and thanks for mu(4e)!
