### ISSUE TITLE
[mu4e bug] `mu4e-search-toggle-property` not shown in `describe-mode` in the headers.

### ISSUE THREAD

**Issue by shamefulCake1** [djcb/mu#2630]
**Describe the bug**
By default, `h` is bound to `describe-mode`. Very convenient.
However, some (at least `mu4e-search-toggle-property`) commands are not displayed there, I don't know why.

**How to Reproduce**

1. Open some headers view, with threads, for the ease of testing.
2. Check that `P` is bound to `mu4e-search-toggle-property` by using it.
3. Run `M-x describe-mode` and search for `mu4e-search-toggle-property`, which is not found.

**Environment**
Please describe the versions of OS, Emacs, mu/mu4e etc. you are using.

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment]
`describe-mode` only shows the bindings for the _major mode_; however the `mu4e-search-toggle-property` (and other `mu4e-search` functions) are in their own _minor mode_ (since they're used outside `mu4e-headers-mode` as well.

So, while it'd be useful to see the minor-mode bindings as well, it's not something that Emacs does, at least not by default. Perhaps ask upstream Emacs?
