### ISSUE TITLE
[mu4e bug] `mu4e-compose-reply` opens buffer twice

### ISSUE THREAD

**Issue by malb** [djcb/mu#2693]
**Describe the bug**

This might well be a "me" problem, but since eda8db0c3b5d08ca8bfee51af4089d86e16d8f81 when I reply to a message, the buffer opens twice: once in a new frame (as desired and setup by me) and one in some other window/frame. When I then close my compose buffer, both frames (the one created for composing and the one used to also display my buffer) are killed.

Reverting eda8db0c3b5d08ca8bfee51af4089d86e16d8f81 fixes the problem for me. 

I think the issue is that `message-pop-to-buffer` calls `pop-to-buffer-same-windows` before `mu4e-compose-mode` was called, but I'm using `display-buffer-alist` which branches on the major-mode of the buffer to decide where to display it. One option could be to revert eda8db0c3b5d08ca8bfee51af4089d86e16d8f81 conditional when `mu4e-compose-switch` is `display-buffer`?

**Environment**

Debian, mu(4e) built from source.

**Checklist**
- [X] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [ ] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [X] you have read all of the above

Please make sure you all items in the checklist are set/met before filing the ticket. Thank you!

**Comment by djcb** [comment]
Hmm... I think the `advice`-code was a mistake, and as you've noticed it's rather error-prone for mu4e to have such code-paths since I won't notice any problem until it's too late.

I see two ways:
- somehow ensure that `message-pop-to-buffer` honors `display-alist` / `display-buffer`
- if that's not (yet) possible, document the `add-advice`; 

Looking at the current implementation, it seems `message-pop-to-buffer` does support a `switch-function` (and I guess `display-buffer` could be used for that)... but we don't control how various function call `message-pop-to-buffer`. So perhaps lobby the Gnus people to make this configurable, don't think I want mu4e trying to hack around that.

Or perhaps I'm totally wrong and am overlooking some simple solution :)

**Comment by malb** [comment]
Maybe a slightly less brittle option would be to `cl-letf` `message-pop-to-buffer`  to `mu4e--fake-pop-to-buffer`?

```emacs-lisp
(cl-letf (((symbol-function 'message-pop-to-buffer) mu4e--fake-pop-to-buffer))           
```

**Comment by djcb** [comment]
Yeah, that's indeed slightly less brittle, but the `add-advice` has the advantage that it can be set outside mu4e.

**Comment by djcb** [comment]
Anyway, I brought back `mu4e--fake-pop-to-buffer`, since all the other non-default `mu4e-compose-switch` such ` frame` and `window` _also_ had problems without. Guess we'll have to live with it...
