### ISSUE TITLE
[mu4e rfe] Duplicate Message Indication

### ISSUE THREAD

**Issue by yamanq** [djcb/mu#2713]
**Is your feature request related to a problem? Please describe.**
Thank you for maintaining mu4e. I manage a gmail account using mu4e, which results in duplicates if a message is labeled. I use automatic labeling to mark certain messages as they arrive into my inbox. However, using mu4e with duplicates hidden, I only see one copy of the message, with no indication that it is a duplicate (and therefore labeled). I do not want to show all duplicates because every message in the Gmail system is duplicated to [Gmail]/All Mail.

**Describe the solution you'd like**
In the Maildir header line on mu4e:view, list all the Maildirs including duplicates.

**Describe alternatives you've considered**
- Include another line in the mu4e:view header such as "Duplicates: <Maildirs>"
- Show an icon in the Flags column that indicates a duplicate. This is not ideal since it doesn't show the user where the duplicate is located.

**Comment by djcb** [comment]
I suspect the "icon in the flags column" one is the only feasible (i.e., not requiring too many changes).

**Comment by djcb** [comment]
That's true; there's no real need to mirror the complete Gmail folder tree, but anyway, I guess I'll have to decline that RFE then, as it's too much work. 

Frankly, the problem is with the mismatch between gmail and the the local file-system. Trying to work around that with mu4e is hard... too much work, so have to decline this... sorry!
