### ISSUE TITLE
[misc] support a post imapnotify `mu index` while mu4e is running

### ISSUE THREAD

**Issue by RyanGibb** [djcb/mu#2734]
I'm not quite sure if this is a bug report or a feature request, but is it possible to `mu index` while mu4e is running? The reason being I use [goimapnotify](https://gitlab.com/shackra/goimapnotify) for receiving mail as fast as I reasonable can, which on a new mail invokes `mbsync`, and runs `mu index` post. This doesn't work when mu4e is running, though, as it takes a lock over the database. Would it be possible to prompt a re-index while mu4e is running to support this workflow at all?

**Comment by djcb** [comment]
Two methods.

1.  Instead of calling `mu index`, you can tell your emacs to invoke `mu4e-update-index`. This is easiest when you use emacsclient, i.e. use something like
```
emacsclient --eval '(mu4e-update-index)' 
```
(assuming mu4e is already running).

2. Ah less elegant method is to kill -2 the mu process before calling `mu index`  (see the FAQ in the manual).

**Comment by RyanGibb** [comment]
Ah, thanks! Sorry I missed that FAQ.
