### ISSUE TITLE
[RFE] mu4e: option to save sent messages as new

### ISSUE THREAD

**Issue by sbruda** [djcb/mu#2743]
Note, please see the IDEAS.org file in repository root for existing ideas; maybe
it's already there.

**Is your feature request related to a problem? Please describe.**
Not a problem, merely a matter of taste: I like to have sent messages saved in the sent folder as new messages.  This way I can easily see the recently sent messages (and have the option to mark them as read or whatnot).

**Describe the solution you'd like**
I would like to have an option (e.g., customizable variable) to turn this feature on, something along the attached patch.

**Describe alternatives you've considered**
I am already running mu4e trivially patched as follows:

`--- mu4e-draft.el.orig	2024-08-18 11:52:05.295292510 -0400`
`+++ mu4e-draft.el	2024-08-18 11:52:23.242090425 -0400`
`@@ -268,7 +268,7 @@`
`             (_ (mu4e-error "Error in ``mu4e-sent-messages-behavior'")))))`
`     (when sent-dir`
`          (mu4e-join-paths`
`-          (mu4e-root-maildir) sent-dir "cur"`
`+          (mu4e-root-maildir) sent-dir "new"`
`           (format "%s%s2,S" base-name mu4e-maildir-info-delimiter)))))`
` `
` `

Obviously a better solution will be to provide a choice on the matter as suggested in the attached patch.

**Additional context**
[mu4e-draft-fcc-patch.txt](https://github.com/user-attachments/files/16650034/mu4e-draft-fcc-patch.txt)

**Comment by djcb** [comment]
When you send a message,  you must  have seen it, so marking it as "unread" would be a bit odd. You should be able to find recently sent message by sorting them by date.

Of course, there's a use-case for _everything_,  but I attempt to limit this kind of niche-customizations since they're the most likely to break with some refactoring. But, perhaps you can use a "SentRecently" folder for sending messages and setup up refiling from there to more permanent location, "Sent"?

Anyway, have to decline this. Sorry!
