### ISSUE TITLE
[RFE] mu3e: ability to edit non-draft messages so that the edits synchronize

### ISSUE THREAD

**Issue by sbruda** [djcb/mu#2744]
Note, please see the IDEAS.org file in repository root for existing ideas; maybe
it's already there.

**Is your feature request related to a problem? Please describe.**
Several of my workflows rely on my ability to edit regular email messages.  This is easily accomplished by eliminating the check for drafts in mu4e-compose-edit, but that message's UID is (obviously)  the same and so the changes are not synchronized with the server at the next offlineimap (or similar) run.

**Describe the solution you'd like**
It would be nice to have the option (perhaps protected by a customizable variable) to enable editing all messages.  Additionally, it would be great if the message UID is changed on editing the message, so that the changes are subsequently synchronized with the server.

I would be more than happy to try any other suggestion you might have on the matter.

**Describe alternatives you've considered**
I am already running a trivially patched version of mu3e as follows:

`--- mu4e-compose.el-orig	2024-08-18 12:27:41.984261120 -0400`
`+++ mu4e-compose.el	2024-08-18 12:28:11.484476898 -0400`
`@@ -441,8 +441,8 @@`
`          "Edit an existing draft message."`
`          (interactive)`
`          (let* ((msg (mu4e-message-at-point)))`
`-           (unless  (member 'draft (mu4e-message-field msg :flags))`
`-             (mu4e-warn "Cannot edit non-draft messages"))`
`            (mu4e--draft`
`             'edit`
`             (lambda ()`

That solves my immediate problem, but it would also be nice (not strictly required, but nice) for the new version of the message to find its way to the server.

**Comment by djcb** [comment]
Hmm, I don't want to make random messages editable, since in general we don't allow changes (except for metadata) to messages. For many messages it's also not possible/feasible to conveniently edit them (think various rich-text/html etc.) message, let alone signed/encrypted messages.

Now, maybe that doesn't apply to your particular use-cases, but in that case I'd recommend you use your patch locally. And you can remove the existing UID, a new one will be generated . If they are your own message, perhaps `mu4e-compose-supersede` can be useful.

So, I'm sorry but I'll have to decline this.
