### ISSUE TITLE
Make multiple-account functionality built-in

### ISSUE THREAD

**Issue by zakkak** [djcb/mu#545]
Why should having multiple accounts in mu4e be that hacky?

What do you think about making mu4e core support multiple accounts just like in the example with `my-mu4e-account-alist` and for configurations with a single account this list would contain a single element.

I came across [this repository](https://github.com/fgallina/mu4e-multi), which might be a good start.

**Comment by djcb** [comment]
Well, I'm usually a little bit hesitant when adding non-trivial chunks of functionality that I don't use myself... since it's hard to fix bugs or even to notice them (e.g., when some change in another part of mu4e affect this).

Anyway, I'd be willing to take something like what's in that repo, as it seems fairly independent, provided that there's also an update for the mu4e-manual.

**Comment by zabbal** [comment]
Excellent idea! Will it work with gpg as well?

**Comment by zakkak** [comment]
It should! I don't see why not.

**Comment by djcb** [comment]
Okay, `mu4e-context` is available in mu master now. Examples in the doc. This provides built-in multi-account (and more).

**Comment by zakkak** [comment]
Thanks @djcb

**Comment by zabbal** [comment]
Great news! Will it be part of 0.9.14 release?

**Comment by djcb** [comment]
@zabbal: next stable version will be 0.9.16 (current 0.9.15 is development / unstable), and yes, this functionality will be there. Still tweaking it a bit / documenting, but it's looking good!

**Comment by gaydenko** [comment]
@djcb , have you, please, rough estimation of 0.9.16 date?

**Comment by djcb** [comment]
Roughly... today!

**Comment by gaydenko** [comment]
Real magic! :)
