### ISSUE TITLE
mu index slow

### ISSUE THREAD

**Issue by mardukbp** [djcb/mu#546]
I am using mu 0.9.11. Every time I check my email after starting up or after a restart it takes nearly a minute to show the unread messages. I have 13,700 messages stored in Maildirs/Account1, Maildirs/Account2, Maildirs/Account3 and I have created `.noupdate` files in the directories that will not receive new messages.

I just ran `mu index --rebuild --maildir /path/to/Maildirs` and it took 68 seconds (201 msg/s). I then cleared the caches as per `man mu-index` and then ran `mu index` and it took 34 seconds (254 msg/s). According to the benchmarks in the manual I expected the second run to take less than a second. If I do not clear the caches, then the second run takes less than a second. I am using a Lenovo Y580. 

UPDATE: Updated mu version from 0.9.9.6 to 0.9.11 and the problem persists.

**Comment by djcb** [comment]
Well, flushing those caches is only to benchmark the "cold" case; hope you're not clearing the caches in the normal (warm) case?

**Comment by mardukbp** [comment]
According to `man mu-index`, flushing the caches and running `mu index` with an existing database should take less than a second. Once the information is cached (the cache is warm) running `mu index` should also take less than a second.

In my case, flushing the caches and running `mu index` with an existing database takes over 30 seconds. Once the information is cached (the cache is warm) running `mu index` takes less than a second. The problem is that the caches are flushed with every restart, shutdown or hibernation.

**Comment by mardukbp** [comment]
Tried with Manjaro and this problem is not happening. I will have to fix my Arch. When I find a solution I will post it here and close this issue.

**Comment by tdavis** [comment]
Did you ever resolve this issue, @mardukbp? I've been having a similar problem though only since switching *from* Arch. Updating used to be lightning fast; now it proceeds at about 3k msg/sec no matter the situation. Even after removing the entire ``.mu`` directory and re-indexing, the second "warm" index (having not fetched any mail) only proceeds at the same 3k/sec and has to process every message. Pretty soon it'll take as long to run the indexing process as offlineimap waits to update mail.

No idea if it's of any use, but here's my configuration table:

```
mu configuration is complete.
------------------------------------------------
mu version                           : 0.9.11

Xapian version                       : 1.2.18
GLib version                         : 2.42.1
GMime version                        : 2.6.20
Guile version                        : 2.0.11
Emacs version                        : GNU Emacs 24.4.1

Have wordexp                         : yes
Build mu4e emacs frontend            : yes
Build 'mug' toy-ui (gtk+/webkit)     : no
McCabe's Cyclomatic Complexity tool  : no

Have direntry->d_ino                 : yes
Have direntry->d_type                : yes
------------------------------------------------
```

**Comment by mardukbp** [comment]
Turns out that the slowness I was experiencing was due to ecryptfs. I switched to dm-crypt and the issue is solved. @tdavis Did you encrypt your home folder?

**Comment by tdavis** [comment]
Oh @mardukbp, how I hate you. It just *had* to be that, didn't it? Couldn't have been something simpler? In a moment of weakness, when Arch was shipping a basically-broken DBus, I switched to Ubuntu temporarily. That switched me from dm-crypt to ecryptfs since I just used their automated setup. I guess I know what I'm doing this weekend...

Thanks a lot for the update, despite the sad tidings!

**Comment by mardukbp** [comment]
I'm glad that my experience helped you and don't forget that hate leads to suffering :laughing:.
