### ISSUE TITLE
Path to embedded images in HTML email uses incorrect path separator

### ISSUE THREAD

**Issue by mankoff** [djcb/mu#572]
When I send an HTML email from in Org following the instructions from http://vxlabs.com/2015/01/28/sending-emails-with-math-and-source-code/ and @cpbotha, the figures are attached, but not shown in mu (in emacs) or in the HTML view in my browser. The path of an example image is:

```html
<div class="figure">
<p><img src="cid:_var_folders_60_jb7kfrsn2jd90hpcgj4m_wrc0000gn_T_ltxpng_latex785keu_42588084df8059f6627def9dc184dd9f7294d6a7.png" alt="\begin{equation}
\int_{42}^\infty = x\,dx
\end{equation}" /></p>
</div>
```

That images exists, but I can only see it if I replace `cid:` with `file://` and then all of the `_` characters with `/`.

**Comment by cpbotha** [comment]
That is the best way to include images with an email: The image is one of the parts in the multipart email, and should have that cid as an identifier. If you view the outgoing message in mu4e, and press `.` you can see all of the parts, including the encoded image part.

If you actually send the mail to a HTML capable client (I use my old gmail account to test), the embedded graphic will display perfectly.

The problem here is that your local browser does not know how to correctly interpret the multipart email. I don't know what mu does when you configure it to view the HTML part (as you mentioned in your other report), mine is configured to view only the text part.

**Comment by mankoff** [comment]
Correct. This is a feature request for `mu4e-action-view-in-browser` to do a search-and-replace on the temp file it creates.

**Comment by djcb** [comment]
The cid: is a reference to the a MIME-part of the e-mail message;
usually, these are just unique identifiers. From the example, it seems
that org's html conversion uses something based on a path. However,
that's just an implementation detail we cannot really depend upon.

And then, this only works on the sending side; the receiving side is
not going to create these files, so we cannot show them there.

What you'd want is for a browser to support cid: and inlines images;
that would indeed be nice, but there's not much that mu/mu4e can do
for that...

**Comment by mankoff** [comment]
Ah. I get it. That image was from when it was sent, not a decoding read. Instead of the browser supporting it, the "view in browser" could be enhanced. But this doesn't seem like something necessary in core mu4e. Hence, closing...
