### ISSUE TITLE
Threading not working for RT (Request Tracker) tickets

### ISSUE THREAD

**Issue by petergil** [djcb/mu#573]
We use Request Tracker (https://www.bestpractical.com/rt/) for issue tracking at  my job. Unfortunately it looks like mu does not detect threading for these tickets. Would it be possible to add support for threading for them?

I have uploaded an example here: https://gist.github.com/petergil/266648adcff37cd01533

**Comment by spacefrogg** [comment]
Your request tracker is broken in this respect. As you can see, it sends out e-mails with the References: field filled out but the `In-Reply-To:` field empty. According to [RFC 2822 (p. 23)](https://www.ietf.org/rfc/rfc2822.txt) this means that both messages are part of a thread but not a direct response to any message of this thread. How then shall mu4e order the messages? Another issue is that both messages are part of the same thread (because the have the same message-id in their `References:` field), but no message with the referenced message-id exists as a parent message. Thus they both start on top of their own, same named, threads. Correct behaviour for the answer would be to carry the content of the `Message-ID:` field of the parent message in its `In-Reply-To:` and `References:` fields.

Short answer: Fix Request Tracker, mu4e is the symptom not the cause.
