### ISSUE TITLE
inline pgp

### ISSUE THREAD

**Issue by cocreature** [djcb/mu#594]
Sadly a lot of people don't use pgp/mime, but of course I still need to read their mail. Currently I just run epa-decrypt-region to do that but it gets annoying to do that all the time manually. More importantly it gets messed up when replying because mu4e inserts the original message and not the buffer content. I looked a bit around and it seems like gmime doesn't support it, so putting that into the backend would probably be a bit annoying. However for the mu4e frontend 99% of the cases could probably be solved by regex matching for an encrypted pgp message and then decrypting using epa and replacing the original message for that. Is there anything wrong with that approach? If not I'll try to implement this (if something else wants to do it, I also would be very happy).

**Comment by thomasf** [comment]
Yeah, this is rather annoying.

**Comment by djcb** [comment]
This seems like something the GMime (the mail parsing library we are using) should do (but doesn't, at the moment).

But a trick in mu4e might work as well; if it's not too messy, it could be added.

**Comment by zakkak** [comment]
The only thing I can think of is regular expressions:

1. If the regular expression matches, capture the content
2. Decrypt / Verify it
3. Replace the matching region with the decrypted content / Remove the pgp headers and add information about the signature

Gnus seems to be able to handle both inline pgp signatures and pgp encryption.

Signature verification needs the following configuration in Gnus:
```
(setq mm-verify-option 'always)
(setq gnus-buttonized-mime-types '("multipart/signed"))
```

Hopefully we could use gnus backend as well and avoid reinventing the wheel.

**Comment by tmalsburg** [comment]
I also find missing support for inline PGP very unfortunate.  One drawback of the mu4e-based solution would be that encrypted emails are not indexed and therefore not searchable.  For that reason, I would personally prefer a mu-based solution.  I have no idea how difficult this would be and I have neither the skill nor the time to work on it.  However, I would (once again) be happy to support someone who is willing to work on it through a bounty.

**Comment by zakkak** [comment]
I believe the best way would be to implement it in the GMime lib.  This way the impact of the contribution would be broader.

**Comment by zakkak** [comment]
Hmm, I forgot about @danmilon's e-mail at the GMime mailing list https://github.com/djcb/mu/issues/59#issuecomment-60933570.

So they guys suggest we should implement it on our side instead of the library.  However, Jeffrey Stedfast says he is willing to consider elegant approaches for inclusion in the library.

**Comment by zakkak** [comment]
@tmalsburg please try a846919.
It's a quick hack to decrypt inline pgp.  After having processed the message with mu and just before processing it to be displayed I invoke `epa-decrypt-armor-in-region`.

Tha drawbacks of this method are:
1. We do not provide information in the usual manner (`:decryption` header)
2. `epa-decrypt-armor-in-region` has a built-in dialog that asks you if you want to inline replace the decrypted message or view it in a temp buffer.

Using the internals of the epa package I believe we can bring it closer to our needs (and support signature verification as well).  Comments are welcome!

**Comment by djcb** [comment]
On possible way might be to pre-process the messages (say, through procmail or some equivalent), and turn the inline-PGP into MIME-based PGP. 

It might also be possible to do such a transformation inside GMime, but I don't know if that'd be considered a clean solution. In any case, even if we added it today, it would take some time before that specific GMime-version is widely available.

Otherwise, something with EPA as suggested could be possible, maybe with a bit of trickery.

**Comment by cslux** [comment]
> 2. epa-decrypt-armor-in-region has a built-in dialog that asks you if you want to inline replace the decrypted message or view it in a temp buffer.

I have recently submitted a patch because of that, unfortunately it will be available only in emacs 25 and above. Right now I have patched my emacs 24.5.1 epa.el with the same patch. This saves me now one keystroke, but still not fully automatic.

The patch a have submitted, adds a defcustom `epa-replace-original-text` and has three option,
always, never and ask.

Commit: https://github.com/emacs-mirror/emacs/commit/ebad964b3afbe5ef77085be94cf566836450c74c
Bug report: http://lists.gnu.org/archive/html/bug-gnu-emacs/2015-11/msg00587.html

Christian

**Comment by cslux** [comment]
@zakkak  I will try your quick hack (https://github.com/zakkak/mu/commit/a846919478358fdc08b76d9963b0421d04f1a547) once I'm at home.

**Comment by tmalsburg** [comment]
One clarification question: I was under the impression that encrypted messages in PGP-Mime format are indexed but when I just searched for the content of such emails, mu didn't return anything.  Is that a bug or did I hallucinate this feature?

**Comment by thomasf** [comment]
Hold on a bit now :)  Even if that was indexing of encrypted e-mail was supported it should never be a default settings.

**Comment by zakkak** [comment]
:+1:  

AFAIR, messages do not get decrypted while indexing (`mu index` does not accept `--decrypt`).

**Comment by djcb** [comment]
Indeed, encrypted messages are indexed, but not decrypted. So you only get the "metadata".

**Comment by tmalsburg** [comment]
Thanks for clarifying.  This means that we're not losing anything if we decrypt PGP inline only in Mu4e, right?  But if that is true, why does mu have support for decryption at all?  Or asked differently: why are PGP-mime messages not decrypted in Emacs as well?

Is indexing of encrypted text already a feature request?  It seems like something that people might want.  If I convince my colleagues and friends to communicate through PGP encrypted messages by default, mu would lose a lot of its value.  I understand that indexing of encrypted message content means that the cleartext is in the index.  But depending of the setup this may not be a problem and if it is, it could be fixed by encrypting the index with the user's PGP key.

**Comment by zakkak** [comment]
> Thanks for clarifying. This means that we're not losing anything if we decrypt PGP inline only in Mu4e, right? But if that is true, why does mu have support for decryption at all? Or asked differently: why are PGP-mime messages not decrypted in Emacs as well?

Decrypting on the mu side allows better integration with the existing work-flow, where `mu4e` acts as a front-end that delegates the handling to `mu`.  Additionally, I was able to reuse some code already available in `mu` since multipart handling was already implemented there and only needed to be extended.

> Is indexing of encrypted text already a feature request?

AFAIR, no.  Although it makes sense in some setups.  Note also that drafts
are not encrypted #425.

> It seems like something that people might want. If I convince my colleagues and friends to communicate through PGP encrypted messages by default, mu would lose a lot of its value. I understand that indexing of encrypted message content means that the cleartext is in the index. But depending of the setup this may not be a problem and if it is, it could be fixed by encrypting the index with the user's PGP key.

The idea of having the option to decrypt messages at `mu index` and encrypt the index sounds good.  I believe you should open another rfe for this :)

**Comment by tmalsburg** [comment]
Thanks @zakkak, this makes sense.  I suppose this means that inline-PGP should better be handled in mu in anticipation of support for the indexing of encrypted mails (see #712).  I don't mind doing `M-x epa-decrypt-mail` when I receive inline-PGP but it's annoying that I can't search for the content of these mails.  So my issue is really separate from OP's.

**Comment by zabbal** [comment]
There is "repair message" functionality in thunderbird which I think deals explicitly with this sort of messages. Maybe it could serve as a reference point.

**Comment by cocreature** [comment]
One important problem in @zakkak hack is that when replying it uses the encrypted text instead of the decrypted one. Probably `mu4e~view-msg` or something like that needs to be set after decrypting.

**Comment by zakkak** [comment]
I think this happens because I placed the *hack* in the mu4e-view function.  When replying to a message,the message body is retrieved through another function.

```
;; 1) When we reply/forward a message, we get it from the backend, ie:
;; we send to the backend (mu4e-compose):
;;     compose type:reply docid:30935
;; backend responds with:
;;      (:compose reply :original ( .... <original message> ))
```

Hence, we also need to patch mu4e-draft.el
I have not tested the bellow patch, but it should do the trick.

``` diff
diff --git a/mu4e/mu4e-draft.el b/mu4e/mu4e-draft.el
index d97d3b6..3f8b64f 100644
--- a/mu4e/mu4e-draft.el
+++ b/mu4e/mu4e-draft.el
@@ -442,6 +442,10 @@ from either `mu4e~draft-reply-construct', or
            (forward (mu4e~draft-forward-construct msg))
            (new     (mu4e~draft-newmsg-construct))
            (t (mu4e-error "unsupported compose-type %S" compose-type))))
+    (when (if (eq mu4e-decryption-policy 'ask)
+              (yes-or-no-p (mu4e-format "Decrypt message?"))
+            mu4e-decryption-policy)
+      (epa-decrypt-armor-in-region (point-min) (point-max)))
        (newline)
        ;; include the message signature (if it's set)
        (if (and mu4e-compose-signature-auto-include mu4e-compose-signature)
```

However, as we discuss above, this approach is probably not the best.

**Comment by djcb** [comment]
Inline pgp in fact works with the new/experimental view based on gnus' article mode at least.

**Comment by djcb** [comment]
So indeed, that's the way forward; add a `(setq mu4e-view-use-gnus t)` _before_ you start `mu4e`.
