### ISSUE TITLE
Duplicate UID

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#613]
I wrote and sent and email today and afterwards isync complained that there is a duplicate UID.  The collision occurred in the sent folder and the new message was the offending message.  I suppose this should not have happened.  Not sure what information would be useful for diagnosing the problem.  Admittedly, I wasn't using a very recent version of mu4e.  I did last update from git probably a couple of weeks ago.  `mu --version` says: 0.9.10

**Comment by shackra** [comment]
This may help you http://tiborsimko.org/mbsync-duplicate-uid.html

**Comment by tmalsburg** [comment]
Thank you, @shackra!

**Comment by jackbaty** [comment]
Tibor's post has been getting me through, but I was getting duplicate UIDs every few times I'd sync. It took me quite some time to discover `setq mu4e-change-filenames-when-moving`. It seems that when using mbsync, moved messages _must_ be renamed so the default causes problems (or did for me). Adding `(setq mu4e-change-filenames-when-moving t)` has prevented further duplicate UID errors due to refiling messages.

**Comment by tmalsburg** [comment]
I have `mu4e-change-filenames-when-moving` set to `t` but I still encounter this problem every few months.

**Comment by djcb** [comment]
The `mu4e-change-filenames-when-moving` does change the filenames mu4e is using, but it does not use the U=2 or whatever (as per  http://tiborsimko.org/mbsync-duplicate-uid.html). So, I think the trick is in that link. I don't think there's much that mu can do here.
