### ISSUE TITLE
Release tarball 0.9.9.6 lacks configure and requires autoreconf -i

### ISSUE THREAD

**Issue by chaoflow** [djcb/mu#661]
https://github.com/djcb/mu/archive/v0.9.9.6.tar.gz

**Comment by jschwab** [comment]
Yes, this is true for github tarballs.  See section 2.2.4 of the installation docs.

http://www.djcbsoftware.nl/code/mu/mu4e/Installation.html

**Comment by chaoflow** [comment]
The newest release seems only to be available on github. You could use a release branch that contains files desirable for a release and create tags and therefore tarballs from there.

**Comment by jschwab** [comment]
Is the autotools requirement a big problem?

**Comment by djcb** [comment]
Yes, jschwab is correct. We used to have proper 'make dist' tarballs through google-code, but since they don't allow that anymore there are only the unconfigured ones from github.

I don't like adding generated files in the mu repo; but perhaps we could have a separate mu-releases repo, just containing those tarballs. Not sure if that's allowed by github, they are (understandably) concerned with people using github as a file dump.

**Comment by chaoflow** [comment]
Workflow proposal for releases:
- merge master into release branch
- generate files in release branch
- tag
- github will provide the release tarball based on the tag.

@djcb The release branch could be in a separate repo, if you don't like the files in the mu repo.

**Comment by djcb** [comment]
I'll put the next release tarball into https://github.com/djcb/mu-releases
