### ISSUE TITLE
Auto Directory detection

### ISSUE THREAD

**Issue by Immortalin** [djcb/mu#711]
Most desktop and mobile email clients e.g. outlook, Mail.app, K9 etc. are able to automatically detect the different folders and do not require as much manual folder configuration for every single account as mu4e. It would be great if mu can also work that way.

**Comment by zakkak** [comment]
Just a clarification. Are you referring to the Trash, Sent and Draft folders?

**Comment by Immortalin** [comment]
Yup, e.g. [this](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bemail/mu4e), it currently requires too much configuration. This adds to complexity and raises the barrier of entry for new users.

**Comment by djcb** [comment]
mu4e can't reliably know which folders are for what, so it would have to make guesses. For some accounts (such as GMail) it might be possible to come up with some defaults of course. 

However, with the examples in the manual it shouldn't take more than a few minutes to set up though - which isn't too much of a time-investment for an email program, I think. There's a bit of complexity that comes with emacs, because it's so flexible - it's hard to hide that completely.
