### ISSUE TITLE
Missing nsplugginwrapper causes emacs to hang

### ISSUE THREAD

**Issue by cpitclaudel** [djcb/mu#723]
Hi,

I've just started looking at mu. I'm using the latest master. Pressing `a v` in an email causes Emacs to hang for a long time. Debugging led to a call to msg2pdf. Reproducing this call in the shell yields:

```
sh: 1: /usr/lib/nspluginwrapper/i386/linux/npviewer: not found
sh: 1: /usr/lib/nspluginwrapper/i386/linux/npviewer: not found
*** NSPlugin Wrapper *** ERROR: failed to execute NSPlugin viewer
*** NSPlugin Wrapper *** ERROR: failed to initialize plugin-side RPC client connection
*** NSPlugin Wrapper *** WARNING:(/build/buildd/nspluginwrapper-1.4.4/src/npw-wrapper.c:3556):invoke_NP_Initialize: assertion failed: (rpc_method_invoke_possible(g_rpc_connection))
sh: 1: /usr/lib/nspluginwrapper/i386/linux/npviewer: not found
*** NSPlugin Wrapper *** ERROR: failed to execute NSPlugin viewer
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
*** NSPlugin Wrapper *** ERROR: failed to initialize plugin-side RPC client connection
*** NSPlugin Wrapper *** WARNING:(/build/buildd/nspluginwrapper-1.4.4/src/npw-wrapper.c:3556):invoke_NP_Initialize: assertion failed: (rpc_method_invoke_possible(g_rpc_connection))
```

Installing nspluginwrapper fixed the problem. It would have been helpful if mu4e had notified me of the missing plugin (or if the makefile had complained)

Thanks!

**Comment by djcb** [comment]
`msg2pdf` is a separate program and it uses webkit through its gtk wrapper, and the error message comes from somewhere around there. It's a dependency (apparently) of that, for the case where you have some flash content; and for some reason, the plugin decides to wait it, rather than to simply not show the flash content. 

Anyway, not much mu/mu4e can do about that, but I've added a note to the docs.
