### ISSUE TITLE
break handling in org~mu4e-mime-convert-to-html

### ISSUE THREAD

**Issue by justmytwospence** [djcb/mu#770]
`org~mu4e-mime-convert-to-html` sets `org-export-preserve-breaks` to nil, which correctly puts each line of quoted replies starting with `>` on its own line. Unfortunately, it also places a `<br>` tag after soft newlines (like caused by `auto-fill-mode` with `use-hard-newlines`), effectively causing the html email to behave like a text/plain email without format=flowed.

Is there a way to get both the soft newlines in the email body and the newlines in the quoted replies to look good at the same time?

**Comment by djcb** [comment]
Note that the experimental org rich-text editing has been deprecated for quite some time already, since there are just too many corner-cases. At some point, this code will go away. Perhaps replace by `org-mime`.

Now, for this particular case, you probably need to massage `org~mu4e-mime-convert-to-html` a bit. Perhaps you can add a step at the beginning where you unfill (ie, remove soft newlines) from parts not starting with ">" (or `message-yank-cited-prefix`).
