### ISSUE TITLE
Calendar invitations sent from Gmail

### ISSUE THREAD

**Issue by peterwvj** [djcb/mu#857]
I'm new to this so please bear with me :) 

When people send me invites to events using Google calendar I receive the event invitation as an attachment to the email. Using Google web-mail I can accept/decline the invitation by clicking either "Yes" or "No":

~~~
Going?   Yes - Maybe - No    more options
~~~

These are just links that can be opened using a web browser, e.g. `https://www.google.com/calendar/event?action=RESPOND&eid=......`

 When I use emacs/mu4e "Yes" and "No" aren't clickable links - they're just plain text. Can this be changed? I mean, it would be useful if I could accept/decline the invitation from emacs.

**Comment by peterwvj** [comment]
For my purposes the `shr` seems to be the best choice of html renderer. It solves my problem and lets me achieve what I want:

```
(require 'mu4e-contrib)
(setq mu4e-html2text-command 'mu4e-shr2text)
```

As an alternative the email can be opened in the web browser:
```
;; a V opens the current message in the default web browsers.
(add-to-list 'mu4e-view-actions '("ViewInBrowser" . mu4e-action-view-in-browser) t)
(setq mu4e-view-show-images t)
```

**Comment by FrostyX** [comment]
Hello @peterwvj,
sorry for resurrecting an old issue. 

The `(setq mu4e-html2text-command 'mu4e-shr2text)` worked for a while but since we now use the new view mode based on gnus, a google calendar invitation is not rendered as HTML email anymore but it uses some icalendar logic instead. I don't understand the details.

There are `[ Accept ]    [ Tentative ]    [ Decline ]` buttons but they don't point to the google calendar. Also, there isn't the `more options` button anymore.  For me personally, this is a regression.

I added this to my config to render invitations as standard HTML emails. 

```elisp
(setq mm-automatic-display
      (remove "text/calendar" mm-automatic-display))
```

Just wanted to share my solution and save others some time.
