### ISSUE TITLE
resend async email. 

### ISSUE THREAD

**Issue by zw963** [djcb/mu#870]
## Expected or desired behavior

Need to resent a async email.

## Actual behavior

When internet is not connect, I sent a email with mu4e,
email is sent, and moved to `Maildir/sent`, But in fact
the email still keep no sent

## Steps to reproduce

Just settings 
```cl
(require 'smtpmail-async)
(setq send-mail-function 'async-smtpmail-send-it      
      message-send-mail-function 'async-smtpmail-send-it
)
```
## Versions of mu, mu4e/emacs, operating system etc.
Git HEAD version.

**Comment by zw963** [comment]
See log (emacs *messages*), I could see:

Sending via mail...
Delivering message to opensuse@opensuse.org...

If internet is available when sent, correct output is:

[mu4e] Message sent
Delivering message to opensuse@opensuse.org...done

Current, my internet is not so stable, is there exist a workaround for this?

thanks

**Comment by zw963** [comment]
Hi, I sent a issue in emacs-async repo, Following is link, with a little discuss.

https://github.com/jwiegley/emacs-async/issues/64

Thanks.

**Comment by djcb** [comment]
Yeah, I think this explains some case where sent mail  never arrived... -- if there's some problem (internet connection or otherwise) sending the mail, mu4e simply does not see it. Not sure how that can be fixed -- ideally, the aync mail send should return an error just like the non-async one does. But that might be hard.

For spotty internet connections, I'd recommend either queued mode (see the mu4 manual), or perhaps use a local smtp server that can cache outgoing mail.

**Comment by djcb** [comment]
So, unfortunately, I don't think mu4e can do much about this. There is in fact already a mention of the silent failures in the mu4e faq (in the manual).
