### ISSUE TITLE
[RFE] Respond to iCalendar invitations

### ISSUE THREAD

**Issue by peterwvj** [djcb/mu#994]
Some email clients (such as Outlook or Gmail) generate RSVP buttons that enable users to respond to icalendar events in a convenient way (by clicking accept, decline or tentative). In mu4e, icalendar events are currently received as email attachments that can be processed using external tools (see #271). However, I think that strengthening the  icalendar integration (by generating RSVP buttons, for example) would make mu4e a much more efficient tool.

After researching this, I found out that gnus already offers RSVP support. Initially, this feature was maintained as a separate tool extension that has now become an official part of gnus/Emacs. The old sources for gnus' RSVP feature can be found in [jtatarik's ical-event](https://github.com/jtatarik/ical-event) repository. In particular, the `ical-event-reply.el` and `ical-event.el` packages seem to have the functionality that is needed create an ical response (based on some appointment request). So if we're lucky the main bulk of the work is to integrate that functionality with mu4e and add the necessary UI stuff (similar to [gnus-calendar.el](https://github.com/jtatarik/ical-event/blob/master/gnus-calendar.el)). If someone can think of a better way to implement this feature then I'm all ears. Any input is highly appreciated.

Workaround (for Gmail users): If you're using Gmail it is possible to have Gmail generate the RSVP buttons for you. All you need to do is to configure mu4e to render emails in HTML (e.g. `(setq mu4e-html2text-command 'mu4e-shr2text)`). However, this won't work if you're using Microsoft Exchange.

Update:

- Discussion about ical support on [reddit](https://www.reddit.com/r/orgmode/comments/5odzem/accept_calendar_invitation_icalics_in_mail/)
- There exists [ical support for notmuch/Emacs](https://github.com/larkery/emacs/blob/master/site-lisp/notmuch-calendar-x.el)

**Comment by felipeochoa** [comment]
Very strong +1 on this. In my view, there are a few different things that need to happen to fully support iCalendar invitations: (more details below)

1. Proper display of event details (summary, location, time, etc.)
2. Tracking of individual events over time (have we responded? is this a new invite or an update? etc.)
3. Simple context-sensitive interface for replying to an invitation

If there's support for this approach, I'd be willing to make this into a PR. I have a clear view of how points 2 and 3 would work, but would need some guidance for cleaning up the implementation of point 1 given that it involves more of mu4e's internals. 

## Displaying event details

I've hacked-together an implementation of point 1 in [this gist](https://gist.github.com/felipeochoa/63e491efd305a71dc5bfc72997036c01). It's a bit ugly since I delegate to `gnus-icalendar-event->gnus-calendar` for formatting, but here's a screenshot of the information added: 

![image](https://user-images.githubusercontent.com/2739312/31068708-8f30d774-a759-11e7-8155-d8bc80451fcf.png)

The implementation uses a bunch of mu4e internals and is generally convoluted since it has to work with two architectural details from mu4e: Attachments can only be requested asynchronously, but the message body is retrieved synchronously. Perhaps it would be better to add a different render path for `*mu4e-view*` when messages are detected as being calendar invites. Maybe even with a flag at the mu level.

## Tracking events over time

I think point 2 is best handled outside of mu4e, by whatever calendar application the user prefers. mu4e should simply define an (asynchronous?) interface for querying and updating event info. Off the top of my head, it should include functionality for accepting/updating/declining an invitation and for querying whether an invitation is outdated and whether the user has responded already. (Outlook and Gmail both include a snippet of the user's diary around the time of the event, but that is non-essential). I imagine with this interface defined, there would emerge standard packages for `mu4e-ical-org`, `mu4e-ical-diary`, `mu4e-ical-gmail`, etc. The default implementation of the interface would be a no-op for accepting/updating/declining invitations and would assume all invitations are current and not responded to.

## Response interface

This part is relatively straightforward, I think, provided we have point 2 settled. For current invites, we add 3 buttons (accept, decline, & tentative) to the event summary. If the user has already responded, we mark which response they've given. Each button funcalls the relevant interface function and then applies logic similar to `gnus-icalendar-reply` to actually mail the response to the organizer

**Comment by edumerco** [comment]
Hola Felipe.

> Very strong +1 on this.  [...]

Another very strong +1. ;)

> 1 Proper display of event details (summary, location, time, 
> etc.) 
> 2 Tracking of individual events over time (have we responded? is 
> this a new invite or an update? etc.) 
> 3 Simple context-sensitive interface for replying to an 
> invitation 

For me, 1 is important, 2 is not so much, and 3 is the crux of 
this topic. 

The issue is that it depends on the calendar solution that each 
person is using (orgmode, google, apple, standard ical, davcal, 
etc.). 

If it's so, we should limit mu4e participation as much as 
possible, giving the possibility to pipe the event information to 
other components/modules.

While it will not make by itself a complete solution, it will make 
it cover more possibilities.

WDYT? :)



-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Comment by felipeochoa** [comment]
Hola @edumerco. 

> For me, 1 is important, 2 is not so much, and 3 is the crux of this topic.

I think this is a matter of preference :) For me 2 is quite important. Either way, though, I agree that mu4e should not turn into a calendar. Rather, it should provide the right set of hooks so that users can plug in whatever calendar system they use.

**Comment by edumerco** [comment]
Hola. 

>> For me, 1 is important, 2 is not so much, and 3 is the crux of 
>> this topic.

> I think this is a matter of preference :) For me 2 is quite 
> important.

Of course, sorry if it sounded too absolute. :)
Since the issue is recurrent, the idea was just to find the common 
relevant point. 

> Either way, though, I agree that mu4e should not turn into a 
> calendar. Rather, it should provide the right set of hooks so 
> that users can plug in whatever calendar system they use.

Yes! :D

What are the most used calendar systems for mu4e users?

Top of my mind I think about orgmode, google, apple...

On, standards, I believe:
+ Ical
+ CalDAV

If someone else is interested, I can make a webform to query what 
our community uses, so we can invest effort on the things that 
will return more common good. :)


-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Comment by djcb** [comment]
https://github.com/emacs-mirror/emacs/blob/master/lisp/gnus/gnus-icalendar.el has support, and mu4e has support for gnus' article-mode now. That at least should help with adding events to the local calendar. 

So guess it's a matter of a little glue? Patches are welcome.

**Comment by peterwvj** [comment]
As explained in this [thread](https://groups.google.com/forum/#!topic/mu-discuss/qXNvsbQjd_U) @djcb recently added experimental integration support for gnus article mode. Since gnus already allows one to respond to calendar events I was able to generate the RSVP buttons (accept, tentative, decline) in mu4e by adding the following to my config:

```elisp
(setq mu4e-view-use-gnus t)
(require 'gnus-icalendar)
(gnus-icalendar-setup)
```

But when I click one of the RSVP buttons I see an error saying `"gnus-summary-select-article: This is a pseudo-article"`. I'm not sure what's missing in order to make it work, but it's a start.

**Comment by Chris00** [comment]
I think the problem with `gnus-icalendar-reply` (the function that is called when you click on the button) is that it tries to call `gnus-icalendar-send-buffer-by-mail`:
```elisp
(defun gnus-icalendar-send-buffer-by-mail (buffer-name subject)
  (let ((message-signature nil))
    (with-current-buffer gnus-summary-buffer
      (gnus-summary-reply)
      (message-goto-body)
      (mml-insert-multipart "alternative")
      (mml-insert-empty-tag 'part 'type "text/plain")
      (mml-attach-buffer buffer-name "text/calendar; method=REPLY; charset=UTF-8")
      (message-goto-subject)
      (delete-region (line-beginning-position) (line-end-position))
      (insert "Subject: " subject)
      (message-send-and-exit))))
```
It tries to replay to the current message with `(gnus-summary-reply)` which is bound to fail as `gnus-summary-buffer` is `" *appease-gnus*"`.  So maybe we have to put a special function for *mu4e* for the text property `'gnus-callback` in order to call an appropriate function for our favorite mailer.  Or maybe we can just hack `gnus-summary-reply` to do what we want...

**Comment by Chris00** [comment]
Please see https://github.com/djcb/mu/pull/1403.
